### ISSUE TITLE
Exuberant ctags not recognized with vim 8

### ISSUE THREAD

**Issue by kcuzner** [majutsushi/tagbar#359] opened 2016-11-03 04:45 UTC
Just upgraded to vim 8 today on Arch Linux (package updated on the 30th of October) and I found that I was unable to open my tagbar. I see the following message:

```
Tagbar: Ctags doesn't seem to be Exuberant Ctags!
BSD ctags will NOT WORK. Please download Exuberant Ctags from ctags.sourceforge.net and install it in a directory in your $PATH or set g:tagbar_ctags_bin.
Executed command: "'ctags' --version"
Command output:
Exuberant Ctags 5.8, Copyright (C) 1996-2009 Darren Hiebert
  Compiled: Oct 24 2014, 14:15:58
  Addresses: <dhiebert@users.sourceforge.net>, http://ctags.sourceforge.net
  Optional compiled features: +wildcards, +regex, +internal-sort
Exit code: -1
````

Here is the debug log:
```
2016-11-02 23:38:40.698986: OpenWindow called with flags: ''
2016-11-02 23:38:40.699411: goto_win(): wincmd p, 1
2016-11-02 23:38:40.699582: goto_win(): wincmd p, 1
2016-11-02 23:38:40.699753: Checking for Exuberant Ctags
2016-11-02 23:38:40.699992: EscapeCtagsCmd called
2016-11-02 23:38:40.700087: ctags_bin: ctags
2016-11-02 23:38:40.700179: ctags_args (is a string): --version
2016-11-02 23:38:40.700411: Escaped ctags command: 'ctags' --version
2016-11-02 23:38:40.700541: Executing ctags command: 'ctags' --version
2016-11-02 23:38:40.710278: Calling shell to execute: "('ctags' --version) >/tmp/vEDuMdU/3 2>&1"
2016-11-02 23:38:40.710417: Exit code: -1
2016-11-02 23:38:40.726319: Tagbar: Ctags doesn't seem to be Exuberant Ctags!
2016-11-02 23:38:40.726459: Command output:
Exuberant Ctags 5.8, Copyright (C) 1996-2009 Darren Hiebert
  Compiled: Oct 24 2014, 14:15:58
  Addresses: <dhiebert@users.sourceforge.net>, http://ctags.sourceforge.net
  Optional compiled features: +wildcards, +regex, +internal-sort

2016-11-02 23:38:40.726567: Exit code: -1
```

I believe that the following check in autoload/tagbar.vim:1153 is causing the problem:

```
if v:shell_error || ctags_output !~# '\(Exuberant\|Universal\) Ctags'
```

I think that v:shell_error is somehow not working properly since when I execute ctags --version in bash the return code is 0:

```
kcuzner@kcuzner-desktop:~$ ctags --version
Exuberant Ctags 5.8, Copyright (C) 1996-2009 Darren Hiebert
  Compiled: Oct 24 2014, 14:15:58
  Addresses: <dhiebert@users.sourceforge.net>, http://ctags.sourceforge.net
  Optional compiled features: +wildcards, +regex, +internal-sort
kcuzner@kcuzner-desktop:~$ echo $?
0
```

I'm unsure if this is a vim problem or a tagbar problem to be honest.

**Comment by kcuzner** [comment] 2016-11-03 04:53
Just noticed that even if I remove the `v:shell_error` test from that line so that it will load the tagbar, when it actually goes to parse the tags `v:shell_error` is also -1 there as well:

```
2016-11-02 23:49:53.057632: ExecuteCtagsOnFile called [/tmp/vc8xlgq/51]
2016-11-02 23:49:53.057807: EscapeCtagsCmd called
2016-11-02 23:49:53.057871: ctags_bin: ctags
2016-11-02 23:49:53.057947: ctags_args (is a list): ['-f', '-', '--format=2', '--excmd=pattern', '--fields=nksSaf', '--extra=', '--file-scope=yes', '--sort=no', '--append=no', '--language-force=python', '--python-kinds=icfmv']
2016-11-02 23:49:53.058176: Escaped ctags command: 'ctags' '-f' '-' '--format=2' '--excmd=pattern' '--fields=nksSaf' '--extra=' '--file-scope=yes' '--sort=no' '--append=no' '--language-force=python' '--python-kinds=icfmv' '/tmp/vc8xlgq/51'
2016-11-02 23:49:53.058285: Executing ctags command: 'ctags' '-f' '-' '--format=2' '--excmd=pattern' '--fields=nksSaf' '--extra=' '--file-scope=yes' '--sort=no' '--append=no' '--language-force=python' '--python-kinds=icfmv' '/tmp/vc8xlgq/51'
2016-11-02 23:49:53.067783: Calling shell to execute: "('ctags' '-f' '-' '--format=2' '--excmd=pattern' '--fields=nksSaf' '--extra=' '--file-scope=yes' '--sort=no' '--append=no' '--language-force=python' '--python-kinds=icfmv' '/tmp/vc8xlgq/51') >/tmp/vc8xlgq/52 2>&1"
2016-11-02 23:49:53.067902: Exit code: -1
2016-11-02 23:49:53.093947: Command output:
2016-11-02 23:49:53.094032: sys	/tmp/vc8xlgq/51	/^import sys$/;"	i	line:3
main	/tmp/vc8xlgq/51	/^def main():$/;"	f	line:6	access:public

2016-11-02 23:49:53.094094: Exit code: -1
             2016-11-02 23:49:53.094418: Ctags error when processing file
2016-11-02 23:49:53.094545: fileinfo empty after processing [/home/kcuzner/Projects/Python/ihexViewer/ihexviewer]
2016-11-02 23:49:53.110857: AutoUpdate called [/home/kcuzner/Projects/Python/ihexViewer/ihexviewer]
2016-11-02 23:49:53.110986: Vim filetype: 'python', sanitized filetype: 'python'
2016-11-02 23:49:53.111052: Checking if file is valid [/home/kcuzner/Projects/Python/ihexViewer/ihexviewer]
2016-11-02 23:49:53.111218: File data outdated, updating [/home/kcuzner/Projects/Python/ihexViewer/ihexviewer]
2016-11-02 23:49:53.111281: ProcessFile called [/home/kcuzner/Projects/Python/ihexViewer/ihexviewer]
2016-11-02 23:49:53.111340: Checking if file is valid [/home/kcuzner/Projects/Python/ihexViewer/ihexviewer]
2016-11-02 23:49:53.111646: typeinfo for file to process: {'ctagstype': 'python', 'ftype': 'python', 'kinddict': {'c': 1, 'v': 4, 'f': 2, 'i': 0, 'm': 3}, 'sro': '.', 'getKind': function('303'), 'createKinddict': function('304'), 'kind2scope': {'c': 'class', 'f': 'function', 'm': 'function'}, 'scope2kind': {'function': 'f', 'class': 'c'}, 'New': function('302'), 'kinds': [{'short': 'i', 'long': 'imports', 'fold': 1, 'stl': 0}, {'short': 'c', 'long': 'classes', 'fold': 0, 'stl': 1}, {'short': 'f', 'long': 'functions', 'fold': 0, 'stl': 1}, {'short': 'm', 'long': 'members', 'fold': 0, 'stl': 1}, {'short': 'v', 'long': 'variables', 'fold': 0, 'stl': 0}]}
2016-11-02 23:49:53.111796: ExecuteCtagsOnFile called [/tmp/vc8xlgq/53]
2016-11-02 23:49:53.111935: EscapeCtagsCmd called
2016-11-02 23:49:53.111987: ctags_bin: ctags
2016-11-02 23:49:53.112051: ctags_args (is a list): ['-f', '-', '--format=2', '--excmd=pattern', '--fields=nksSaf', '--extra=', '--file-scope=yes', '--sort=no', '--append=no', '--language-force=python', '--python-kinds=icfmv']
2016-11-02 23:49:53.112334: Escaped ctags command: 'ctags' '-f' '-' '--format=2' '--excmd=pattern' '--fields=nksSaf' '--extra=' '--file-scope=yes' '--sort=no' '--append=no' '--language-force=python' '--python-kinds=icfmv' '/tmp/vc8xlgq/53'
2016-11-02 23:49:53.112421: Executing ctags command: 'ctags' '-f' '-' '--format=2' '--excmd=pattern' '--fields=nksSaf' '--extra=' '--file-scope=yes' '--sort=no' '--append=no' '--language-force=python' '--python-kinds=icfmv' '/tmp/vc8xlgq/53'
2016-11-02 23:49:53.123877: Calling shell to execute: "('ctags' '-f' '-' '--format=2' '--excmd=pattern' '--fields=nksSaf' '--extra=' '--file-scope=yes' '--sort=no' '--append=no' '--language-force=python' '--python-kinds=icfmv' '/tmp/vc8xlgq/53') >/tmp/vc8xlgq/54 2>&1"
2016-11-02 23:49:53.123987: Exit code: -1
2016-11-02 23:49:53.149498: Command output:
2016-11-02 23:49:53.149570: sys	/tmp/vc8xlgq/53	/^import sys$/;"	i	line:3
main	/tmp/vc8xlgq/53	/^def main():$/;"	f	line:6	access:public

2016-11-02 23:49:53.149624: Exit code: -1
2016-11-02 23:49:53.149763: Ctags error when processing file
2016-11-02 23:49:53.149863: fileinfo empty after processing [/home/kcuzner/Projects/Python/ihexViewer/ihexviewer]
2016-11-02 23:49:53.149940: OpenWindow finished
2016-11-02 23:49:53.149990: ToggleWindow finished
2016-11-02 23:49:54.510710: AutoUpdate called [/home/kcuzner/Projects/Python/ihexViewer/NERD_tree_1]
2016-11-02 23:49:54.510970: Vim filetype: 'nerdtree', sanitized filetype: 'nerdtree'
2016-11-02 23:49:54.511068: Checking if file is valid [/home/kcuzner/Projects/Python/ihexViewer/NERD_tree_1]
2016-11-02 23:49:54.511239: File not readable
2016-11-02 23:49:54.511320: Not a valid file, stopping processing
```

**Comment by majutsushi** [comment] 2016-11-03 05:14
This is a duplicate of #352. It seems to be recently introduced bug in Vim and is being tracked at https://github.com/vim/vim/issues/1196 .

**Closed** 2016-11-03 05:14 UTC
