### ISSUE TITLE
tagbar can not exists correctly 

### ISSUE THREAD

**Issue by ucasFL** [majutsushi/tagbar#440] opened 2017-09-05 15:01 UTC
When existed tagbar, some last characters of the words left in the screen. 
![selection_001](https://user-images.githubusercontent.com/22127746/30067638-e55c767a-928d-11e7-995f-67a51fe6fbd5.png)
![selection_002](https://user-images.githubusercontent.com/22127746/30067639-e57824ba-928d-11e7-93c8-044c03cad42d.png)
Operating System: Ubuntu 16.04 
vim version: 7.4

**Comment by majutsushi** [comment] 2017-09-05 23:04
This looks like graphics corruption that is caused by a bug somewhere in the software stack between Vim and the graphics card driver. Does it go away if you press <kbd>Ctrl</kbd>+<kbd>l</kbd>? This is almost certainly not a bug in Tagbar.

**Comment by ucasFL** [comment] 2017-09-06 06:12
yeah, when I press down `Ctrl`+`l`, they were disappeared, but why is that?

**Comment by majutsushi** [comment] 2017-09-06 09:31
Because that redraws the screen (see `:h CTRL-L`), removing any artifacts that are left over from improper updates earlier. So this is clearly a bug in the graphics stack somewhere, and nothing that Tagbar has control over. Unfortunately I can't really help more than that because there are so many places where the bug could be. I would recommend trying to update your system to see if it has been fixed in a newer version of whatever is causing it.

**Closed by majutsushi** 2017-09-06 09:31 UTC

**Comment by ucasFL** [comment] 2017-09-06 10:35
ok, thank you!
