### ISSUE TITLE
Tagbar scope/folds?

### ISSUE THREAD

**Issue by JesseLeite** [majutsushi/tagbar#459] opened 2017-11-24 16:31 UTC
I feel stupid asking this question, I apologize if this is wrong forum, but I just installed tagbar in Vim8 with universal-ctags, and I get these foldable namespace scopes, which doesn't seem consistent with what I've seen elsewhere on internet?  Curious what I might be doing wrong?

![](http://b3.ms/qpknazj1MBRJ)

**Comment by Luxed** [comment] 2017-11-29 22:04
@JesseLeite I haven't tested PHP with ctags yet.
Would it be possible that the structure of the project does that ? Would it be possible to know the `tree` structure of the project ?

**Comment by JesseLeite** [comment] 2017-11-30 17:57
Hi @Luxed :)  It's pretty much a standard laravel app structure [as seen here](https://github.com/laravel/laravel).  That said, I have two co-workers who use Tagbar in the same laravel app, and they don't see what I'm seeing.

**Comment by Luxed** [comment] 2017-11-30 22:06
What is your ctags version (`ctags --version`) (Compare the entire output with your co-workers).

Are you sure your plugin is updated (or their plugin is outdated) ?

Maybe compare the output of `ctags AddressRequiredWith.php` too (this will create a tags file where you are).

Appart from that, I just started using the plugin, so I don't really know. Maybe activating logs would be great (if there are some).

**Comment by JesseLeite** [comment] 2017-12-01 01:40
<img width="1021" alt="screen shot 2017-11-30 at 8 39 35 pm" src="https://user-images.githubusercontent.com/5187394/33464111-b89fc79e-d60e-11e7-9401-68bd099f73e9.png">

**Comment by majutsushi** [comment] 2017-12-03 02:37
Could you give an example of what you were expecting to see? I don't really use PHP myself so I'm not quite sure what you mean.

Could it be related to the change in #430?

**Comment by JesseLeite** [comment] 2017-12-04 19:32
Hey @majutsushi ah yeah it does look like it's related to #430.  My co-worker sees this:

![screen shot 2017-12-04 at 2 30 05 pm](https://user-images.githubusercontent.com/5187394/33571991-a80f7728-d8ff-11e7-83db-706d67938cc6.png)

I see this:

![screen shot 2017-12-04 at 2 29 30 pm](https://user-images.githubusercontent.com/5187394/33571958-9363da80-d8ff-11e7-8e9f-bcf19688d8af.png)

Reading through documentation, but I don't see how to toggle back to the non-heirarchy-style view for PHP files, do you know if there's a way?  I know it's more information, but it's much easier to parse through a non-collapsable list most of the time IMO.

**Comment by majutsushi** [comment] 2017-12-17 02:47
There isn't really a way to switch between a hierarchical and a non-hierarchical view in Tagbar, since its main purpose, and distinguishing feature from the previous TagList plugin, is the hierarchical view. It would certainly be possible to implement this, but so far there hasn't been any demand for it, and I'm not sure how generally useful it would be. So for now I'm inclined to close this issue as "working as intended". Also note that you can set the "compact" option to get rid of the empty lines between tags in the second image.

**Closed by majutsushi** 2017-12-17 02:47 UTC

**Comment by JesseLeite** [comment] 2017-12-18 14:16
@majutsushi it's not that bad, though I can't stand the [use aliases] section.  I always want the actual class, trait, property, or method; Almost never want the use/import statement.  Is there a way to disable just that [use aliases] section so that I don't have to scroll past it every time?

**Comment by Luxed** [comment] 2017-12-18 14:37
@JesseLeite What about creating a custom PHP profile that's the same as in the code but without [this](https://github.com/majutsushi/tagbar/blob/master/autoload/tagbar/types/uctags.vim#L686) line ?
It should remove the unwanted alias section.
Once again this is just a suggestion, @majutsushi should be able to give you more information on how it is done.

**Comment by JesseLeite** [comment] 2018-02-12 16:49
@Luxed Oh interesting! How would I go about creating a custom PHP profile in my vimrc to do this?
