### ISSUE TITLE
no tags found for rust

### ISSUE THREAD

**Issue by guoyunlong16** [majutsushi/tagbar#590] opened 2020-02-02 00:50 UTC
I install and configure tagbar for neovim according to README, but get the `no tags found` error.

Versions:
Ubuntu: 18.04
neovim: 0.4.3
tagbar: 679a9d (2020-01-23)
ctags: 
```
Universal Ctags 0.0.0(e0a976d7), Copyright (C) 2015 Universal Ctags Team
Universal Ctags is derived from Exuberant Ctags.
Exuberant Ctags 5.8, Copyright (C) 1996-2009 Darren Hiebert
  Compiled: Dec 16 2019, 17:58:44
```

configuration:
```
Plug 'majutsushi/tagbar'    
let g:tagbar_width=100    
nmap <silent> fu :TagbarToggle<CR>    
let g:tagbar_type_rust = {    
  \ 'ctagsbin' : '/snap/bin/ctags',    
  \ 'ctagstype' : 'rust',    
  \ 'kinds' : [    
      \ 'n:modules',    
      \ 's:structures:1',    
      \ 'i:interfaces',    
      \ 'c:implementations',    
      \ 'f:functions:1',    
      \ 'g:enumerations:1',    
      \ 't:type aliases:1:0',    
      \ 'v:constants:1:0',    
      \ 'M:macros:1',    
      \ 'm:fields:1:0',    
      \ 'e:enum variants:1:0',    
      \ 'P:methods:1',    
  \ ],    
  \ 'sro': '::',    
  \ 'kind2scope' : {     
      \ 'n': 'module',     
      \ 's': 'struct',    
      \ 'i': 'interface',    
      \ 'c': 'implementation',    
      \ 'f': 'function',    
      \ 'g': 'enum',
      \ 't': 'typedef',
      \ 'v': 'variable',
      \ 'M': 'macro',
      \ 'm': 'field',
      \ 'e': 'enumerator',
      \ 'P': 'method',
  \ },
\ }
```

I run the following command with ctags:
`ctags -f - --format=2 --excmd=pattern --extras= --fields=nksaSmt src/main.rs`
and get some tags:
`main	src/main.rs	/^fn main() {$/;"	f	line:1	signature:()`

What's wrong?

**Comment by alerque** [comment] 2020-02-02 05:01
I don't know, but a working config for rust should be included upstream so this works out of the box.

**Comment by alerque** [comment] 2020-02-02 05:48
I just had a look and Rust lang support **is** already baked in out of the box. Where did you get that tag support code and did you try it without any custom config at all? It should work without you having to add `let g:tagbar_type_rust = ...` at al.

**Comment by guoyunlong16** [comment] 2020-02-02 07:13
> I just had a look and Rust lang support **is** already baked in out of the box. Where did you get that tag support code and did you try it without any custom config at all? It should work without you having to add `let g:tagbar_type_rust = ...` at al.

I had a try just now and it doesn't work if I commented `let g:tagbar_type_rust = ...`. In addition, I followed [https://github.com/majutsushi/tagbar/wiki#universal-ctags-variant](url)  for configuration.

**Comment by alerque** [comment] 2020-05-29 19:47
This issue is a duplicate of #568. I'm sorry I missed this is your logs the first time, but the issue is you are using a Snap package for your `ctags`, which cannot read the system's `/tmp` file space.

In #610 we provided a way to disable the cache mechanism that uses temp files and also fixed the error message about not being able to read the cache file.

**Closed by alerque** 2020-05-29 19:47 UTC
Labels: ctags, language-support, question
