### ISSUE TITLE
how to config the g:tagbar_type_typescript ?

### ISSUE THREAD

**Issue by EternalChildren** [majutsushi/tagbar#543] opened 2019-07-03 08:55 UTC
following is ctags for typescript:
```
#LETTER NAME       ENABLED REFONLY NROLES MASTER DESCRIPTION
C       constant   yes     no      0      NONE   constants
G       generator  yes     no      0      NONE   generators
a       alias      yes     no      0      NONE   aliases
c       class      yes     no      0      NONE   classes
e       enumerator yes     no      0      NONE   enumerators (values inside an enumeration)
f       function   yes     no      0      NONE   functions
g       enum       yes     no      0      NONE   enums
i       interface  yes     no      0      NONE   interfaces
l       local      no      no      0      NONE   local variables
m       method     yes     no      0      NONE   methods
n       namespace  yes     no      0      NONE   namespaces
p       property   yes     no      0      NONE   properties
v       variable   yes     no      0      NONE   variables
z       parameter  no      no      0      NONE   function parameters inside function definitions
```
my .vimrc
```
let g:tagbar_type_typescript = {
    \ 'ctagstype' : 'typescript',
    \ 'kinds'     : [
      \ 'C:constant',
      \ 'G:generator',
      \ 'a:alias',
      \ 'c:class',
      \ 'e:enumerator',
      \ 'f:function',
      \ 'g:enum',
      \ 'i:interface',
      \ 'm:method',
      \ 'n:namespace',
      \ 'p:property',
      \ 'v:variable',
      \ 'z:parameter'
    \ ],
    \ 'sro'        : '.',
    \ 'kind2scope' : {
      \ 'C' : 'contant',
      \ 'c' : 'class'
    \ }
\ }
```
i fond some example in doc. but i can't understand the meaning about ":0:1" in "kinds"

in my tags file
![image](https://user-images.githubusercontent.com/27210994/60577803-a802b500-9db2-11e9-867b-080afa9fc506.png)
you can see it have a interface HomeMainProps. and have four props in this interface, but in tagbar window. it's not togehter in HomeMainProps
![image](https://user-images.githubusercontent.com/27210994/60577945-ed26e700-9db2-11e9-9a0c-9035d54e7ad9.png)

so how can i config the tagbar_type_typescript?
can let me get a right interface

**Comment by alerque** [comment] 2019-10-22 10:47
This appears to be a duplicate of issue #496. I'm sure there is a way to do this, but I'm not sure off the top of my head what that is. When somebody does work out the configuration I'd love to see it contributed as a PR!

**Closed by alerque** 2019-10-22 10:47 UTC
