### ISSUE TITLE
vim exit when switch to help file

### ISSUE THREAD

**Issue by xxvv** [majutsushi/tagbar#271] opened 2015-05-29 00:45 UTC
i)let only tagbar.txt in current window
:help tagbar 
:only

ii)open tagbar and switch to tagbar.txt buffer
:TagbarToggle
CTRL-W w

iii)vim exit

-------------------------------------------------------------------------------------------------
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled May 28 2015 15:02:56)
Included patches: 1-729
Compiled by root@hhu

**Comment by mpetazzoni** [comment] 2015-06-03 00:11
I'm having issues with TagBar making Vim quit when closing buffers too. I've been able to track it down to the TagBar plugin, but it's hard to identify in what conditions it happens (it doesn't happen all the time, but very often does).

**Comment by alekgr** [comment] 2015-06-08 21:35
@mpetazzoni I just started using Tagbar. I'm not sure if this is related but when using :ball when tagbar is open it close vim completely

**Comment by majutsushi** [comment] 2016-10-19 22:08
This should be fixed after #234, at least I can't reproduce it. Please reopen if you can still reproduce it.

**Closed by majutsushi** 2016-10-19 22:08 UTC
