### ISSUE TITLE
Multifile tag mode suggestion.

### ISSUE THREAD

**Issue by PavloSolntsev** [majutsushi/tagbar#362] opened 2016-11-18 14:34 UTC
Hi,

First of all I like tagbar and use it. But I found that one functionality is missed. It is the ability to show all tags for specified files or from tags file. This functionality is present in TagList plugin but tag bar just looks better and I don't want to have multiple plugins with almost the same functionality. As potential solution a command to show all tags from tags file can be implemented something to :TagbarAddFiles *.cpp *.h and :TagbarAddTags 

It will be worth to have another function: TagbarModeSwitch. This function may show/hide tags from selected files or the tags file and will allow possibility to switch between single file and multifile modes. 

Unfortunately, I am not VIM script developer and can't help with coding but I can help with testing or something else. 

Let me know what you think about my suggestions. 

Thanks.

**Comment by majutsushi** [comment] 2016-12-10 02:49
This is a duplicate of #31. I would like to keep Tagbar itself rather single-purpose to only display the tags of the current file like a normal IDE would, especially since keeping track of an entire project introduces a lot of complications. I agree that some way to do that would be useful, though.

**Closed by majutsushi** 2016-12-10 02:49 UTC
