### ISSUE TITLE
When reloading files, errors are thrown

### ISSUE THREAD

**Issue by c9s** [majutsushi/tagbar#281] opened 2015-07-06 14:32 UTC
<img width="633" alt="screenshot 2015-07-06 22 31 40" src="https://cloud.githubusercontent.com/assets/50894/8524613/e7266698-242e-11e5-88fd-d9e930ae7fe6.png">

**Comment by majutsushi** [comment] 2016-10-21 10:45
I am unable to reproduce this, and I'm not even sure this is something that can be fixed in Tagbar. The only one that can supply a range to that function is Vim itself, and if that range is invalid that Tagbar can't do anything about this. Can you give an example of how exactly to reproduce this?

**Comment by alerque** [comment] 2019-12-03 10:17
I've fixed a few bugs recently that might have cropped  up in some cases when reloading _the plugin itself_. Perhaps the way your are handling sessions was triggering one of these cases.

I'm reasonably confident this will be fixed now and am closing the issue. If it turns out you still have some issue with this feel free to comment and we'll re-evaluate.

**Closed by alerque** 2019-12-03 10:17 UTC
Labels: unreproducible
