### ISSUE TITLE
Must have a ctags binary in $PATH in order to use jsctags for javascript files

### ISSUE THREAD

**Issue by fsworld009** [majutsushi/tagbar#323] opened 2016-06-27 19:29 UTC
I'm using Windows 7 x64 with neovim-qt

I only work for javascript files so I don't need ctags, I've installed [jsctags](https://github.com/ramitos/jsctags) and I can execute jsctags from cmd, so it is already in $PATH 

I've installed Tagbar and [tern_for_vim](https://github.com/ternjs/tern_for_vim) plugin

When I toggle Tagbar, I get an error message:
> Tagbar: Exuberant ctags not found!
> Please download Exuberant Ctags from ctags.sourceforge.net and install it in a directory in your $PATH or set g:tagbar_ctags_bin.

If I put a ctags.exe file and properly set $PATH, then Tagbar can execute and use jsctags to parse my file automatically (I know it is using jsctags because the result is different if I remove jsctags from $PATH)

I think for javascript files, if there is jsctags available, the plugin should ignore the checks for ctags.

I'll test it again when I have access to my Macbook.

**Comment by majutsushi** [comment] 2016-10-10 09:06
Duplicate of #94 

Yes, this is a bit unfortunate at the moment, but as I mention in the linked issue it's not that straightforward to solve. I still hope to finish my plugin library that abstracts all of this better, but until then I'm afraid I probably won't be able to fix it.

**Closed by majutsushi** 2016-10-10 09:06 UTC
