### ISSUE TITLE
Tagbar: Ctags doesn't seem to be Exuberant Ctags! again

### ISSUE THREAD

**Issue by osDanielLee** [majutsushi/tagbar#365] opened 2016-11-22 09:24 UTC
Hi, 
when I use tagbar, error happened like below:

Tagbar: Ctags doesn't seem to be Exuberant Ctags!
BSD ctags will NOT WORK. Please download Exuberant Ctags from ctags.sourceforge.net and install it in a directory in your $PATH or set g:tagbar_ctags_bin.
Executed command: "'ctags' --version"
Command output:
/Library/Developer/CommandLineTools/usr/bin/ctags: illegal option -- -
usage: ctags [-BFadtuwvx] [-f tagsfile] file ...
Exit code: 1
Press ENTER or type command to continue

I've find the same error as https://github.com/majutsushi/tagbar/issues/225 but it cause by another reason, it's totally not the same, but "Tagbar: Ctags doesn't seem to be Exuberant Ctags!
" again.

**Comment by osDanielLee** [comment] 2016-11-22 09:54
Good news, I've found the reason why error here.
There are two ctags known as GNU ctags and exuberant-ctags, what the tagbar need to use is exuberant-ctags. exuberant-ctags need to be installed by yourself. 

What I do to solve this problem is 
`brew install ctags-exuberant`
and find it's installed in /usr/local/Cellar/ctags/5.8_1
then I add a line in .vimrc:
`let g:Tlist_Ctags_Cmd='/usr/local/Cellar/ctags/5.8_1/bin/ctags'`

then it work well.

So, @majutsushi you could close this issue now. Thx for your amazing tagbar.

**Comment by tarikgraba** [comment] 2016-11-22 12:20
Same Error here.
I'm using a custom universal ctags (from ctags.io) with vim 8.0.49 on Debian Testing.
It used to work correctly  with vim 7.xx

**Comment by osDanielLee** [comment] 2016-11-22 12:31
@tarikgraba As my second message said, the problem you encounter may be related with using GNU ctags probably. In my case I didn't change the version of vim and just setup a ctags-exuberant, add one line to state g:Tlist_Ctags_Cmd make vim know what ctags to use, it works very well.

**Comment by tarikgraba** [comment] 2016-11-22 12:57
No, I'm using really using "exuberant ctags"
The complete error message I get is:
BSD ctags will NOT WORK. Please download Exuberant Ctags from ctags.sourceforge.net and install it in a directory in your $PATH or set 
g:tagbar_ctags_bin.
Executed command: "'/xxxx/local/bin/ctags' --version"
Command output:
Universal Ctags 0.0.0(ef8e60d), Copyright (C) 2015 Universal Ctags Team
Universal Ctags is derived from Exuberant Ctags.
Exuberant Ctags 5.8, Copyright (C) 1996-2009 Darren Hiebert
  Compiled: Feb 16 2016, 14:17:48
  URL: https://ctags.io/
  Optional compiled features: +wildcards, +regex, +option-directory, +coproc, +xpath
Exit code: -1

**Comment by tarikgraba** [comment] 2016-11-22 12:59
In addition, the same version of "Exuberant Ctags" works perfectly with vim 7.4 (bundled with Debian stable)

**Comment by osDanielLee** [comment] 2016-11-22 13:10
It's so weird. "BSD ctags will NOT WORK. Please download Exuberant Ctags from ctags.sourceforge.net and install it in a directory in your $PATH or set
" shows that the ctags is still not right yet, but the next error info show you're running a Exuberant Ctags, maybe a little incompatible I guess. I don't know...

**Comment by Margular** [comment] 2016-11-23 04:36
I get the same issue.

Tagbar: Ctags doesn't seem to be Exuberant Ctags!
BSD ctags will NOT WORK. Please download Exuberant Ctags from ctags.sourceforge.net and install it in a directory in your $PATH or set g:tagbar_ctags_bin.
Executed command: "'ctags-exuberant' --version"
Command output:
Exuberant Ctags 5.9~svn20110310, Copyright (C) 1996-2009 Darren Hiebert
  Addresses: <dhiebert@users.sourceforge.net>, http://ctags.sourceforge.net
  Optional compiled features: +wildcards, +regex
Exit code: -1

**Comment by majutsushi** [comment] 2016-11-23 09:24
There are two issues involved here. The first one is the one that the message is mainly about, the fact that BSD ctags is not compatible with Tagbar. The ctags that is distributed with XCode is BSD ctags, and so @osDanielLee was seeing the message for that reason. Universal Ctags has been compatible with Tagbar for quite some time now.

The second issue is a Vim bug that was introduced in Vim 8.0.36 and got fixed in 8.0.71, and was discussed in #352. So if you're using a Vim version between that and you're seeing that message you will unfortunately have to update Vim to a newer version.

**Closed by majutsushi** 2016-11-23 09:24 UTC

**Comment by tarikgraba** [comment] 2016-11-23 10:30
Ok, I'll wait for a vim update in Debian.

THX

**Comment by tarikgraba** [comment] 2016-11-25 08:21
I can confirm that everything is back to normal with the last version of vim (8.0.95) available on Debian Testing

**Comment by jmarrec** [comment] 2019-04-05 16:23
Hello, I'm hitting the same issue on Windows 10 with Vim 8.1 and Universal Ctags

```
Tagbar: Ctags doesn't seem to be Exuberant Ctags!
BSD ctags will NOT WORK. Please download Exuberant Ctags from ctags.sourceforge.net and install it in a directory in your $PATH or set g:tagbar_ctags_bin.
Executed command: "ctags --version"
Command output:
Universal Ctags 0.0.0(07796eab), Copyright (C) 2015 Universal Ctags Team
Universal Ctags is derived from Exuberant Ctags.
Exuberant Ctags 5.8, Copyright (C) 1996-2009 Darren Hiebert
  Compiled: Apr  5 2019, 00:08:34
  URL: https://ctags.io/
  Optional compiled features: +win32, +wildcards, +regex, +internal-sort, +iconv, +option-directory, +xpath, +json, +interactive, +yaml, +case-insensitive-filenames, +packcc
Exit code: 1
```

```

```VIM - Vi IMproved 8.1 (2018 May 18, compiled Apr  4 2019 22:02:15)
MS-Windows 64-bit GUI version with OLE support
Included patches: 1-1119
Compiled by appveyor@APPVYR-WIN
Huge version with GUI.  Features included (+) or not (-):
+acl                +clientserver       +diff               +float              +libcall            +multi_lang         +python/dyn         +syntax             +title              +wildmenu
+arabic             +clipboard          +digraphs           +folding            +linebreak          +mzscheme/dyn       +python3/dyn        +tag_binary         +toolbar            +windows
+autocmd            +cmdline_compl      +directx            -footer             +lispindent         +netbeans_intg      +quickfix           -tag_old_static     +user_commands      +writebackup
+autochdir          +cmdline_hist       -dnd                +gettext/dyn        +listcmds           +num64              +reltime            -tag_any_white      +vartabs            -xfontset
+autoservername     +cmdline_info       -ebcdic             -hangul_input       +localmap           +ole                +rightleft          +tcl/dyn            +vertsplit          -xim
+balloon_eval       +comments           +emacs_tags         +iconv/dyn          +lua/dyn            +packages           +ruby/dyn           -termguicolors      +virtualedit        +xpm_w32
-balloon_eval_term  +conceal            +eval               +insert_expand      +menu               +path_extra         +scrollbind         +terminal           +visual             -xterm_save
+browse             +cryptv             +ex_extra           +job                +mksession          +perl/dyn           +signs              -termresponse       +visualextra        
++builtin_terms     +cscope             +extra_search       +jumplist           +modify_fname       +persistent_undo    +smartindent        +textobjects        +viminfo            
+byte_offset        +cursorbind         -farsi              +keymap             +mouse              -postscript         +startuptime        +textprop           +vreplace           
+channel            +cursorshape        +file_in_path       +lambda             +mouseshape         +printer            +statusline         -tgetent            -vtp                
+cindent            +dialog_con_gui     +find_in_path       +langmap            +multi_byte_ime/dyn +profile            -sun_workshop       +timers             +wildignore         
   system vimrc file: "$VIM\vimrc"
     user vimrc file: "$HOME\_vimrc"
 2nd user vimrc file: "$HOME\vimfiles\vimrc"
 3rd user vimrc file: "$VIM\_vimrc"
      user exrc file: "$HOME\_exrc"
  2nd user exrc file: "$VIM\_exrc"
  system gvimrc file: "$VIM\gvimrc"
    user gvimrc file: "$HOME\_gvimrc"
2nd user gvimrc file: "$HOME\vimfiles\gvimrc"
3rd user gvimrc file: "$VIM\_gvimrc"
       defaults file: "$VIMRUNTIME\defaults.vim"
    system menu file: "$VIMRUNTIME\menu.vim"
Compilation: cl -c /W3 /nologo  -I. -Iproto -DHAVE_PATHDEF -DWIN32  -DFEAT_CSCOPE -DFEAT_TERMINAL -DFEAT_NETBEANS_INTG -DFEAT_JOB_CHANNEL   -DFEAT_XPM_W32   -DWINVER=0x0501 -D_WIN32_WINNT=0x0501 /MP -DHAVE_STDINT_H /Ox /GL -DNDEBUG  /Zl /MT -DFEAT_OLE -DFEAT_MBYTE_IME -DDYNAMIC_IME -DFEAT_GUI_MSWIN -DFEAT_DIRECTX -DDYNAMIC_DIRECTX -DFEAT_DIRECTX_COLOR_EMOJI -DDYNAMIC_ICONV -DDYNAMIC_GETTEXT -DFEAT_TCL -DDYNAMIC_TCL -DDYNAMIC_TCL_DLL=\"tcl86t.dll\" -DDYNAMIC_TCL_VER=\"8.6\" -DFEAT_LUA -DDYNAMIC_LUA -DDYNAMIC_LUA_DLL=\"lua53.dll\" -DFEAT_PYTHON -DDYNAMIC_PYTHON -DDYNAMIC_PYTHON_DLL=\"python27.dll\" -DFEAT_PYTHON3 -DDYNAMIC_PYTHON3 -DDYNAMIC_PYTHON3_DLL=\"python37.dll\" -DFEAT_MZSCHEME -I "C:\Program Files\Racket\include" -DMZ_PRECISE_GC -DDYNAMIC_MZSCHEME -DDYNAMIC_MZSCH_DLL=\"libracket3m_a36fs8.dll\" -DDYNAMIC_MZGC_DLL=\"libracket3m_a36fs8.dll\" -DFEAT_PERL -DPERL_IMPLICIT_CONTEXT -DPERL_IMPLICIT_SYS -DDYNAMIC_PERL -DDYNAMIC_PERL_DLL=\"perl528.dll\" -DFEAT_RUBY -DDYNAMIC_RUBY -DDYNAMIC_RUBY_VER=24 -DDYNAMIC_RUBY_DLL=\"x64-msvcrt-ruby240.dll\" -DFEAT_HUGE /Fd.\ObjGXOULYHTRZAMD64/ /Zi
Linking: link  /nologo /subsystem:windows,5.02 /opt:ref /LTCG:STATUS /HIGHENTROPYVA:NO oldnames.lib kernel32.lib advapi32.lib shell32.lib gdi32.lib  comdlg32.lib ole32.lib netapi32.lib uuid.lib /machine:AMD64 gdi32.lib version.lib   winspool.lib comctl32.lib advapi32.lib shell32.lib netapi32.lib  /machine:AMD64  libcmt.lib oleaut32.lib user32.lib  /nodefaultlib:lua53.lib  /STACK:8388608  /nodefaultlib:python27.lib /nodefaultlib:python37.lib   "C:\Tcl\lib\tclstub86.lib" WSock32.lib xpm\x64\lib-vc14\libXpm.lib /PDB:gvim.pdb -debug

**Comment by jmarrec** [comment] 2019-04-05 16:26
I just went to fetch the latest exhuberant ctags from sourceforge like indicated and I have the same issue

```
Tagbar: Ctags doesn't seem to be Exuberant Ctags!
BSD ctags will NOT WORK. Please download Exuberant Ctags from ctags.sourceforge.net and install it in a directory in your $PATH or set g:tagbar_ctags_bin.
Executed command: "ctags --version"
Command output:
Exuberant Ctags 5.8, Copyright (C) 1996-2009 Darren Hiebert
  Compiled: Jul  9 2009, 17:05:35
  Addresses: <dhiebert@users.sourceforge.net>, http://ctags.sourceforge.net
  Optional compiled features: +win32, +regex, +internal-sort
Exit code: 1
```

**Comment by emeentag** [comment] 2019-06-13 13:08
**I had this issue with:**
```Exuberant Ctags 5.8, Copyright (C) 1996-2009 Darren Hiebert
  Compiled: Sep 17 2017, 20:48:43
  Addresses: <dhiebert@users.sourceforge.net>, http://ctags.sourceforge.net
  Optional compiled features: +wildcards, +regex```

**the error:**
```BSD ctags will NOT WORK. Please download Exuberant Ctags from ctags.sourceforge.net and install it in a directory in your $PATH or set g:tagbar_ctags_bin.```

Solution:
1. Install ctags over brew `brew install ctags`
2. Add this alias to your bash profile `alias ctags=/usr/local/bin/ctags` or `alias ctags=`brew --prefix`/bin/ctags`
3. Add this  to your .vimrc `let g:tagbar_ctags_bin = "/usr/local/bin/ctags"`

In my case tagbar plugin needs this ctags so this was the reason of error.

**Comment by wxknxxzj** [comment] 2020-09-28 02:05
Is there a solution for spacevim?  It seems to be different from vim's configuration file.
![图片](https://user-images.githubusercontent.com/69200664/94383291-2bf04c00-0172-11eb-8c90-b0363cea3a0d.png)

**Comment by alerque** [comment] 2020-09-28 10:21
@wxknxxzj Please first try using Universal Ctags instead, Exuberant support is going away. Secondly if you continue to have trouble please open a new issue, this one is way overloaded with problems that aren't all the same anyway and it's closed. A new issue will be better for your problem.
