### ISSUE TITLE
:bd closes gvim when TagBar is open

### ISSUE THREAD

**Issue by cbates-** [majutsushi/tagbar#234] opened 2014-12-08 20:46 UTC
Win7 x32.  Starting gvim from PowerShell console.
- .cs file in current buffer.
- :TagbarOpen
- Focus is in buffer with .cs file
- :bd  -- gvim closes

When starting vim.exe from PowerShell, :bd behaves as expected when TagBar is open.

UPDATE:
More experimenting indicates this problem is intermittent.  I thought it was due to using TagBarToggle instead of TagBarOpen, but that does not seem to always be the case.
Strange.

**Comment by fsteinmetz** [comment] 2015-02-13 14:43
Would there be a problem with simply removing function `QuitIfOnlyWindow()`?
Currently I find the behaviour quite disturbing, because vim may close on `:bd` (which would never happen otherwise), or even if you have a help window + a standard window open with tagbar open, and close the standard window.
Skipping this function seems to do the trick. I don't think it would be a problem if in some cases tagbar is the only window left (vim does the same with a quickfix list - taglist does also the same) - at least it's better than losing the inactive buffers. But I don't know tagbar's internals, would there be some side-effects ?

**Comment by mpetazzoni** [comment] 2015-06-03 00:13
I'm running into this as well; makes Vim quit unexpectedly, even if the buffer I delete is not the last one.

**Comment by gus** [comment] 2015-11-06 16:09
Ran into this as well. As a quick fix, I mapped the following `:bp | bd #`; switch to the previous buffer then delete the one I just switched from. Works for now, but won't close the last buffer of course.

**Comment by jackgu1988** [comment] 2016-07-17 14:14
What if you check how many buffers are open before quitting? http://superuser.com/questions/345520/vim-number-of-total-buffers

**Comment by majutsushi** [comment] 2016-10-10 08:54
I think this should finally be fixed with commit e4cfe8a. The implementation is slightly dirty but seems to work according to my tests. Let me know if there are still issues!

**Closed by majutsushi** 2016-10-10 08:54 UTC

**Comment by mpetazzoni** [comment] 2016-10-10 23:40
So, there is definitely an improvement, but I'm still running into some issues with it.

Having the tagbar open, closing a Java source file's buffer works fine, but not closing a reStructuredText file (it seems to go into some sort of infinite loop? Thankfully I can `^C` out of it). Note that this doesn't happen if the reStructuredText file is the only buffer that I had open. But if I open another file, and come back to the rST file and attempt to close that buffer (with the tagbar open), it goes into the loop.

**Comment by jackgu1988** [comment] 2016-10-11 01:02
Is there a difference between an rST file and a "normal" file? Are you sure there isn't something else in your .vimrc causing the loop?

**Comment by majutsushi** [comment] 2016-10-11 08:33
Hmm, I can't reproduce that. Are you using the configuration from the wiki and the `rst2ctags` tool? What version of Vim are you using?

**Comment by majutsushi** [comment] 2016-10-11 09:10
Okay, there seems to be a race condition between certain commands and autocommands. I'll try to dig into it.

**Comment by mpetazzoni** [comment] 2016-10-11 15:08
Hmm, actually, it might simply be my fault. I had this in my `.vimrc`:

```
au BufEnter * nested :call tagbar#autoopen(0)
```

I'm still trying to find a way to have the tagbar automatically open when I enter a file (if possible only on files that I know can have tags), and automatically close when I close the last buffer.

**Comment by majutsushi** [comment] 2016-10-15 07:16
Okay, after spending all Saturday on this I think I finally got it working properly, both in the normal case and the `autoopen()` case. It has to do something that's discouraged by the Vim documentation, but it seems to work and otherwise I don't think there would be a way to make it work at all with the current Vim functionality.
