### ISSUE TITLE
(Win10) Message "BSD ctags will NOT WORK", but only if Vim is started as normal user

### ISSUE THREAD

**Issue by pandel** [majutsushi/tagbar#594] opened 2020-03-10 12:48 UTC
Hi!

Strange problem here. Tried to use tagbar with universal ctags (ctags-2020-03-09_6b6abbf2-x64.zip) under Vim 8.2 (gvim_8.2.0368_x64_signed.exe) with Windows 10 x64.

What happens is, that if I start gVim as normal user, Tagbar does NOT work, and gVim is showing the "BSD ctags... blabla" message.

BUT, if I start gVim as administrator (via elevated command prompt), everything works fine.

I already tried to change access rights to the folders where Vim and ctags are installed, but that didn't change anything. Here is the complete message I get:

```Tagbar: Ctags doesn't seem to be Exuberant Ctags!
BSD ctags will NOT WORK. Please download Exuberant Ctags from ctags.sourceforge.net and install it in a directory in your $PATH or set g:tagbar_ctags_bin.
Executed command: ""C:\Program Files (x86)\Vim\ctags\ctags.exe" --version"
Command output:
Universal Ctags 0.0.0(6b6abbf2), Copyright (C) 2015 Universal Ctags Team
Universal Ctags is derived from Exuberant Ctags.
Exuberant Ctags 5.8, Copyright (C) 1996-2009 Darren Hiebert
  Compiled: Mar  9 2020, 00:28:25
  URL: https://ctags.io/
  Optional compiled features: +win32, +wildcards, +regex, +internal-sort, +unix-path-separator, +iconv, +option-directory, +xpath, +json, +interactive, +yaml, +case-insensitive-filenames, +packcc
Exit code: 1
```

Any ideas on how to make it work as normal user?

Regards,
Holger

**Comment by alerque** [comment] 2020-03-10 15:43
I don't know a lot about Windows paths, but I suspect this has to do with the order it searches for and finds app. I image as your user it has one path and finds some other ctags first, while as an administrator it finds the one you want it to first.

**Comment by alerque** [comment] 2020-03-10 15:47
Looking closer at your output, it looks like it _is_ finding a universal-ctags to run, but in reading it's `--version` output to examine the version it did spit out the help info but then returned an error code at the end! The exit code 1 means it thought it couldn't run. When I run `ctags --version` on my (Linux) system it returns `exit 0` which means a success.

**Comment by pandel** [comment] 2020-03-10 18:12
Yes, I verified that there is no other ctags version on my computer. And if I start this one and only ctags.exe manually from the (unelevated) command prompt, it *seems* to behave normally whatsoever... I also saw exit code 1, but I it clearly does its job actually. Very strange... but thanks for taking care, I think I have to live with starting Vim as admin...

**Comment by alerque** [comment] 2020-03-11 11:10
@pandel I'm going to close this issue because I'm pretty sure tagbar itself is doing the _right_ thing by checking the error code and failing if it returns an error. That being said if somebody with Windows expertise here steps ind and suggests there is some workaround we need to apply I'd be happy to consider it.

I'm going to guess that this is being caused by a "bug" in ctags itself combined with your usage. You are probably (guessing here, so don't take this personal) used to running more things than you should be as Administrator. My guess in this case is that you ran it as Administrator once to check something out or edit something that actually required those privs, and it wrong a file (or files) with elevated priviledges that you now cannot overwrite as your regular user. I'd hazard a guess that if you cleanup up all the possible temp file locations and the `tags` file itself and everything in your project to be owned by your user and not Administrator, you should be able to run as your user just fine.

I don't know what tools Windows has for this, but on Unix I'd use something like `strace ctags` to get an idea of what files and directories ctags was trying to access and which ones it was actually failing on.

**Closed by alerque** 2020-03-11 11:10 UTC

**Comment by alerque** [comment] 2020-03-11 20:14
Interesting note on the topic if `ctags`' exit codes, Snap packages have a similar problem returning a failure code even when they actually did work. See #568.
