### ISSUE TITLE
Ctags doesn't seem to be Exuberant Ctags.. but it is!

### ISSUE THREAD

**Issue by carmelzuk** [majutsushi/tagbar#352] opened 2016-10-19 10:15 UTC
when I run :TagbarToggle I get the following

```
Tagbar: Ctags doesn't seem to be Exuberant Ctags!
BSD ctags will NOT WORK. Please download Exuberant Ctags from ctags.sourceforge.net and install it in a directory in your $PATH or set g:tagbar_ctags_bin.
Executed command: "'/home/carmel/src/ctag_exuberant/ctags-5.8/build/bin/ctags' --version"
Command output:
Exuberant Ctags 5.8, Copyright (C) 1996-2009 Darren Hiebert
    Compiled: Oct 19 2016, 10:36:10
  Addresses: <dhiebert@users.sourceforge.net>, http://ctags.sourceforge.net
  Optional compiled features: +wildcards, +regex
```

debug log gives me:

```
2016-10-19 12:50:49.675579: ToggleWindow called
2016-10-19 12:50:49.676271: OpenWindow called with flags: ''
2016-10-19 12:50:49.676924: goto_win(): wincmd p, 1
2016-10-19 12:50:49.677394: goto_win(): wincmd p, 1
2016-10-19 12:50:49.677756: Checking for Exuberant Ctags
2016-10-19 12:50:49.678349: EscapeCtagsCmd called
2016-10-19 12:50:49.678561: ctags_bin: /home/carmel/src/ctag_exuberant/ctags-5.8/build/bin/ctags
2016-10-19 12:50:49.678777: ctags_args (is a string): --version
2016-10-19 12:50:49.679347: Escaped ctags command: '/home/carmel/src/ctag_exuberant/ctags-5.8/build/bin/ctags' --version
2016-10-19 12:50:49.679867: Executing ctags command: '/home/carmel/src/ctag_exuberant/ctags-5.8/build/bin/ctags' --version
2016-10-19 12:50:49.684208: Calling shell to execute: "('/home/carmel/src/ctag_exuberant/ctags-5.8/build/bin/ctags' --version) >/tmp/vRGrTP3/1 2>&1"
2016-10-19 12:50:49.693066: Tagbar: Ctags doesn't seem to be Exuberant Ctags!
2016-10-19 12:50:49.693150: Command output:
Exuberant Ctags 5.8, Copyright (C) 1996-2009 Darren Hiebert
  Compiled: Oct 19 2016, 10:36:10
  Addresses: <dhiebert@users.sourceforge.net>, http://ctags.sourceforge.net
  Optional compiled features: +wildcards, +regex

                                                2016-10-19 12:50:49.693422: ToggleWindow finished
```

looking in file ~/.vim/bundle/tagbar/autoload/tagbar.vim (line 1139):
`if v:shell_error || ctags_output !~# '\(Exuberant\|Universal\) Ctags'`

v:shell_error is -1
so i guess it has something to do with this variable.. but I can't find the reason for this.

any ideas?

thanks

**Comment by majutsushi** [comment] 2016-10-21 04:58
Huh, that's very strange. Apparently it's executing ctags successfully, but the exit code indicates failure. I don't really have a good idea how this could happen.

How did you determine that `v:shell_error` is `-1`? Did you add some debugging to the script? I've just pushed a change that also prints the exit code if something goes wrong, it would be great if you could reproduce the issue with that just to confirm that the exit code is actually not 0.

Have you tried executing ctags manually in a shell exactly like Tagbar is trying to execute it? Could you please have a look what `echo $?` prints right after ctags manually? Thanks!

**Comment by majutsushi** [comment] 2016-10-21 04:59
Also, what operating system/distribution are you using?

**Comment by majutsushi** [comment] 2016-10-21 05:03
And what shell?

**Comment by Kingwzb** [comment] 2016-10-22 10:51
I also experienced exactly the same issue, my system is Ubuntu 16.04.1 LTS and vim is compile from latest git, and after I deleted the v:shell_error || part from if clause, the tagbar buffer can show up but always empty without showing any error on screen for my cpp files

**Comment by Kingwzb** [comment] 2016-10-22 10:58
and after I deleted vim 8.0 and installed system packaged vim 7.4, it is working now, maybe vim 8.0 related

**Comment by hexchain** [comment] 2016-10-24 02:46
Got this problem too.

```
~ $ which ctags
/usr/bin/ctags
~ $ ctags --version
Exuberant Ctags 5.8, Copyright (C) 1996-2009 Darren Hiebert
  Compiled: Oct 24 2014, 14:15:58
  Addresses: <dhiebert@users.sourceforge.net>, http://ctags.sourceforge.net
  Optional compiled features: +wildcards, +regex, +internal-sort
~ $ vim --version
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Oct 23 2016 19:28:10)
Included patches: 1-46
Compiled by Arch Linux
~ $ pacman -Q gvim vim-runtime ctags 
gvim 8.0.0046-1
vim-runtime 8.0.0046-1
ctags 5.8-5
```

**Comment by majutsushi** [comment] 2016-10-24 03:00
Can someone who is affected by this please generate a log file as explained in `:h tagbar-issues` with the current version?

**Comment by hexchain** [comment] 2016-10-24 03:04
Sure, sorry.
```
2016-10-24 11:03:39.027113: ToggleWindow called
2016-10-24 11:03:39.027381: OpenWindow called with flags: ''
2016-10-24 11:03:39.027622: goto_win(): wincmd p, 1
2016-10-24 11:03:39.027789: goto_win(): wincmd p, 1
2016-10-24 11:03:39.027935: Checking for Exuberant Ctags
2016-10-24 11:03:39.028164: EscapeCtagsCmd called
2016-10-24 11:03:39.028253: ctags_bin: ctags
2016-10-24 11:03:39.028330: ctags_args (is a string): --version
2016-10-24 11:03:39.028515: Escaped ctags command: 'ctags' --version
2016-10-24 11:03:39.028627: Executing ctags command: 'ctags' --version
2016-10-24 11:03:39.040863: Calling shell to execute: "('ctags' --version) >/tmp/vbTLW3y/12 2>&1"
2016-10-24 11:03:39.053946: Tagbar: Ctags doesn't seem to be Exuberant Ctags!
2016-10-24 11:03:39.054025: Command output:
Exuberant Ctags 5.8, Copyright (C) 1996-2009 Darren Hiebert
  Compiled: Oct 24 2014, 14:15:58
  Addresses: <dhiebert@users.sourceforge.net>, http://ctags.sourceforge.net
  Optional compiled features: +wildcards, +regex, +internal-sort

2016-10-24 11:03:39.054078: Exit code: -1
             2016-10-24 11:03:39.054287: ToggleWindow finished
```

**Comment by majutsushi** [comment] 2016-10-24 04:45
Very strange. This looks like a Vim bug to me. The documentation is not really clear in what situations exactly `v:shell_error` has the value `-1`, but I'm unable to reproduce it with a simple test.

What is the result of these commands?
```
:call system('ctags') | echo v:shell_error
:call system('ctags --version') | echo v:shell_error
```

**Comment by hexchain** [comment] 2016-10-24 04:49
These 2 commands returns 1 and 0 respectively.

**Comment by majutsushi** [comment] 2016-10-24 05:20
:expressionless: This is really confusing. I wonder what's different in these two cases.

What's the output of `:set shell?`? I also just added a new debug statement directly after the `system()` call, could you please create a log file again with that just to check that the `v:shell_error` variable doesn't get changed in-between the call and the error message?

**Comment by hexchain** [comment] 2016-10-24 05:26
`:set shell`: `shell=/bin/bash`
```
2016-10-24 13:24:50.189402: ToggleWindow called
2016-10-24 13:24:50.189582: OpenWindow called with flags: ''
2016-10-24 13:24:50.189709: goto_win(): wincmd p, 1
2016-10-24 13:24:50.189798: goto_win(): wincmd p, 1
2016-10-24 13:24:50.189870: Checking for Exuberant Ctags
2016-10-24 13:24:50.190003: EscapeCtagsCmd called
2016-10-24 13:24:50.190045: ctags_bin: ctags
2016-10-24 13:24:50.190083: ctags_args (is a string): --version
2016-10-24 13:24:50.190186: Escaped ctags command: 'ctags' --version
2016-10-24 13:24:50.190241: Executing ctags command: 'ctags' --version
2016-10-24 13:24:50.197741: Calling shell to execute: "('ctags' --version) >/tmp/vPZPwPt/9 2>&1"
2016-10-24 13:24:50.197826: Exit code: -1
2016-10-24 13:24:50.202008: Tagbar: Ctags doesn't seem to be Exuberant Ctags!
2016-10-24 13:24:50.202086: Command output:
Exuberant Ctags 5.8, Copyright (C) 1996-2009 Darren Hiebert
  Compiled: Oct 24 2014, 14:15:58
  Addresses: <dhiebert@users.sourceforge.net>, http://ctags.sourceforge.net
  Optional compiled features: +wildcards, +regex, +internal-sort

2016-10-24 13:24:50.202138: Exit code: -1
             2016-10-24 13:24:50.202349: ToggleWindow finished
```

**Comment by majutsushi** [comment] 2016-10-24 05:34
Hmmm. Sounds like this requires some more investigation.
Just to be sure, did you execute the two commands I mentioned above like they appear now? I edited them a bit shortly after posting.

**Comment by hexchain** [comment] 2016-10-24 05:39
Yes, and I tried again to be sure.

This is probably a vim issue. I downgraded vim to 8.0.0013-1 and the problem disappeared.

**Comment by majutsushi** [comment] 2016-10-24 05:43
Okay, thanks! I'll see whether I can reproduce it with different Vim versions.

**Comment by hg8** [comment] 2016-10-25 07:37
I am also affected by this issue.

    $ which ctags 
    /usr/bin/ctags

    $ ctags --version
    Exuberant Ctags 5.8, Copyright (C) 1996-2009 Darren Hiebert
      Compiled: Oct 24 2014, 14:15:58
      Addresses: <dhiebert@users.sourceforge.net>, http://ctags.sourceforge.net
      Optional compiled features: +wildcards, +regex, +internal-sort

    $ vim --version
    VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Oct 23 2016 19:29:29)
    Included patches: 1-46
    Compiled by Arch Linux
 

    $ pacman -Q vim vim-runtime ctags 
    vim 8.0.0046-1
    vim-runtime 8.0.0046-1
    ctags 5.8-5

    $ cat tagbardebug.log
    2016-10-25 09:32:57.458295: OpenWindow called with flags: 'fcj'
    2016-10-25 09:32:57.458770: goto_win(): wincmd p, 1
    2016-10-25 09:32:57.458966: goto_win(): wincmd p, 1
    2016-10-25 09:32:57.459139: Checking for Exuberant Ctags
    2016-10-25 09:32:57.459416: EscapeCtagsCmd called
    2016-10-25 09:32:57.459522: ctags_bin: ctags
    2016-10-25 09:32:57.459626: ctags_args (is a string): --version
    2016-10-25 09:32:57.459896: Escaped ctags command: 'ctags' --version
    2016-10-25 09:32:57.460047: Executing ctags command: 'ctags' --version
    2016-10-25 09:32:57.472414: Calling shell to execute: "('ctags' --version) >/tmp/vU6HkZH/3 2>&1"
    2016-10-25 09:32:57.472561: Exit code: -1
    2016-10-25 09:32:57.492447: Tagbar: Ctags doesn't seem to be Exuberant Ctags!
    2016-10-25 09:32:57.492538: Command output:
    Exuberant Ctags 5.8, Copyright (C) 1996-2009 Darren Hiebert
       Compiled: Oct 24 2014, 14:15:58
       Addresses: <dhiebert@users.sourceforge.net>, http://ctags.sourceforge.net
       Optional compiled features: +wildcards, +regex, +internal-sort

    2016-10-25 09:32:57.492602: Exit code: -1

    :call system("'ctags'") | echo v:shell_error
    1
    :call system("'ctags' --version") | echo v:shell_error
    0
    :set shell
    shell=/usr/bin/zsh

**Comment by majutsushi** [comment] 2016-10-25 09:21
I'm at a bit of a loss here. I've even installed Arch Linux in a VM, but I'm still not able to reproduce it with these versions:

```
$ pacman -Q vim vim-runtime ctags                                                      
vim 8.0.0046-2
vim-runtime 8.0.0046-2
ctags 5.8-5
```

I'm especially wondering why calling `system()` directly doesn't seem to exhibit this behaviour. I wonder if it has to do with the few shell options that get changed in the `s:ExecuteCtags()` functions. It would be really great if someone affected by this could manage to produce a minimal script file that exhibits this behaviour by removing everything unnecessary from Tagbar. I assume that not much more than (some of) that function should be necessary.

**Comment by hexchain** [comment] 2016-10-25 09:33
I have a `test.vimrc` which is as simple as:
```
set nocompatible
filetype on
set rtp+=~/.vim/bundle/tagbar
```

Calling vim with `vim -u test.vimrc -c TagbarOpen` opens the Tagbar correctly, but if I start vim first, then type `:TagbarOpen` (or `:TagbarToggle`), I'll run into this issue.

**Comment by ralfthewise** [comment] 2016-10-25 19:06
I am also experiencing this.  Running Ubuntu 15.10 x64 with vim built from source.  The steps described by @hexchain in https://github.com/majutsushi/tagbar/issues/352#issuecomment-255985714 are a minimal repro case.  Output of `vim --version`:

```
$ vim --version
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Oct 25 2016 10:41:25)
Included patches: 1-46
Compiled by tim@adams
Huge version with GTK2 GUI.  Features included (+) or not (-):
+acl             +file_in_path    +mouse_sgr       +tag_old_static
+arabic          +find_in_path    -mouse_sysmouse  -tag_any_white
+autocmd         +float           +mouse_urxvt     -tcl
+balloon_eval    +folding         +mouse_xterm     +termguicolors
+browse          -footer          +multi_byte      +terminfo
++builtin_terms  +fork()          +multi_lang      +termresponse
+byte_offset     +gettext         -mzscheme        +textobjects
+channel         -hangul_input    +netbeans_intg   +timers
+cindent         +iconv           +num64           +title
+clientserver    +insert_expand   +packages        +toolbar
+clipboard       +job             +path_extra      +user_commands
+cmdline_compl   +jumplist        -perl            +vertsplit
+cmdline_hist    +keymap          +persistent_undo +virtualedit
+cmdline_info    +lambda          +postscript      +visual
+comments        +langmap         +printer         +visualextra
+conceal         +libcall         +profile         +viminfo
+cryptv          +linebreak       +python          +vreplace
+cscope          +lispindent      -python3         +wildignore
+cursorbind      +listcmds        +quickfix        +wildmenu
+cursorshape     +localmap        +reltime         +windows
+dialog_con_gui  -lua             +rightleft       +writebackup
+diff            +menu            +ruby            +X11
+digraphs        +mksession       +scrollbind      -xfontset
+dnd             +modify_fname    +signs           +xim
-ebcdic          +mouse           +smartindent     +xpm
+emacs_tags      +mouseshape      +startuptime     +xsmp_interact
+eval            +mouse_dec       +statusline      +xterm_clipboard
+ex_extra        +mouse_gpm       -sun_workshop    -xterm_save
+extra_search    -mouse_jsbterm   +syntax          
+farsi           +mouse_netterm   +tag_binary      
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  system gvimrc file: "$VIM/gvimrc"
    user gvimrc file: "$HOME/.gvimrc"
2nd user gvimrc file: "~/.vim/gvimrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
    system menu file: "$VIMRUNTIME/menu.vim"
  fall-back for $VIM: "/usr/local/vim/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_GTK  -pthread -I/usr/include/gtk-2.0 -I/usr/lib/x86_64-linux-gnu/gtk-2.0/include -I/usr/include/gio-unix-2.0/ -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/libpng12 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libpng12 -I/usr/include/pango-1.0 -I/usr/include/harfbuzz -I/usr/include/pango-1.0 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/freetype2    -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1      
Linking: gcc   -L. -fstack-protector -rdynamic -Wl,-export-dynamic  -L/usr/local/lib -Wl,--as-needed -o vim   -lgtk-x11-2.0 -lgdk-x11-2.0 -lpangocairo-1.0 -latk-1.0 -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lpangoft2-1.0 -lpango-1.0 -lgobject-2.0 -lglib-2.0 -lfontconfig -lfreetype  -lSM -lICE -lXpm -lXt -lX11 -lXdmcp -lSM -lICE  -lm -ltinfo -lnsl  -lselinux  -lacl -lattr -lgpm -ldl    -L/usr/lib/python2.7/config-x86_64-linux-gnu -lpython2.7 -lpthread -ldl -lutil -lm -Xlinker -export-dynamic -Wl,-O1 -Wl,-Bsymbolic-functions   -Wl,-R/usr/local/rvm/rubies/ruby-2.2.1/lib -L/usr/local/rvm/rubies/ruby-2.2.1/lib -lruby -lpthread -ldl -lcrypt -lm  -L/usr/local/rvm/rubies/ruby-2.2.1/lib
```

On a possibly related note, if I remove the `v:shell_error` check and then try using `Tagbar` on a `go` file, it no longer works with `gotags`:

```
Tagbar: Could not execute ctags for /home/tim/dev/go/ralfthewise/foo/main.go!
Executed command: "'gotags'  -sort -silent  '/tmp/v3iwUMr/5.go'"
Command output:
!_TAG_FILE_FORMAT^I2
!_TAG_FILE_SORTED^I1^I/0=unsorted, 1=sorted/
...

<a bunch more output>
```

**Comment by majutsushi** [comment] 2016-10-26 02:50
Thanks for this minimal example! Unfortunately there still seems to be something else involved, because even with that I'm not able to reproduce it. But since this demonstrates that the problem seems to be with Vim itself, could you maybe please open an issue at https://github.com/vim/vim/issues? The people there would probably know more about how to deal with this.

**Comment by hexchain** [comment] 2016-10-26 03:13
The test cases mentioned in https://github.com/majutsushi/tagbar/issues/352#issuecomment-256153337 only work when

1. `'nocompatible'` is set (`vim -N` or set option)
2. NOT in startup phase, i.e. not when `vim -N -u test.vimrc` or `vim -N -u NONE '+so test.vimrc'`, but `vim -N -u NONE` then `:so test.vimrc` successfully triggers the problem.

**Comment by majutsushi** [comment] 2016-10-26 03:59
Not for me for some reason :confused: 
But thanks for creating that issue!

**Comment by skgbanga** [comment] 2016-10-29 01:19
btw, a weird datapoint: If I use tagbar with vim8 on a machine in which I have ssh'ed, it works. But on that machine, it gives the above error. :|

**Comment by hexchain** [comment] 2016-10-29 03:54
@skgbanga Could you please dump all environment variables in SSH/non-SSH and do a diff? Thanks.

**Comment by solter** [comment] 2016-10-30 19:47
This still seems to be a problem for vim8 with patches 1-54.

**Comment by astavonin** [comment] 2016-11-06 03:12
Same issue on macOS. Ctags was installed from Brew (it's Exuberant Ctags, see Tagbar diagnostic output below).  Vim version 8.0.57 (form Brew as well). Latest version of Tagbar (installed and updated thru Vundle).

Executed command: "'/usr/local/bin/ctags' --version"
Command output:
Exuberant Ctags 5.8, Copyright (C) 1996-2009 Darren Hiebert
  Compiled: Sep 13 2015, 03:28:50
  Addresses: <dhiebert@users.sourceforge.net>, http://ctags.sourceforge.net
  Optional compiled features: +wildcards, +regex
Exit code: -1

**Comment by hexchain** [comment] 2016-11-06 11:10
@astavonin Could you please do the simple test described in https://github.com/vim/vim/issues/1196? Thanks.

**Comment by astavonin** [comment] 2016-11-06 11:27
Sure!
`vim -N -u repro`
`silent shell_error: 0 something2`

and:

`vim -N -u NONE` then `:so repro`:
silent shell_error: 0 something2

**Comment by astavonin** [comment] 2016-11-07 04:32
Works fine with Vim 8.0.66

**Comment by hexchain** [comment] 2016-11-08 02:08
Looks like it's fixed in https://github.com/vim/vim/commit/c4d4ac22f78fb1394c79eccc8a1e6812c0c7d8a7.

**Comment by majutsushi** [comment] 2016-11-08 05:08
Great! Just to be extra sure, can you confirm that Tagbar works again with Vim 8.0.71?

Thanks for your help in fixing this!

**Comment by hexchain** [comment] 2016-11-08 05:16
Yeah, it works again with Vim 8.0.71.

**Comment by majutsushi** [comment] 2016-11-08 07:05
Excellent, thanks! I'm going to close this issue then.

**Closed by majutsushi** 2016-11-08 07:05 UTC
Labels: vim-bug

**Comment by JC1738** [comment] 2018-01-25 23:01
@majutsushi I am receiving the same problem with nvim 0.2.2 is there a version that gets the Tagbar to accept gotags?  Thank you.
