### ISSUE TITLE
Why does tagbar call ctags even if I haven't open tagbar, and it freeze my GVim.exe for 5-6s sometimes

### ISSUE THREAD

**Issue by skywind3000** [majutsushi/tagbar#475] opened 2018-01-27 14:42 UTC
My GVim sometimes got stuck for 5-6 seconds on my laptop (win 10) & desktop (win 7).

I spent weeks to investigate the reason. And finally found in vim's profile log that tagbar were refreshing in the background even if I haven't open it for a long time. 

The profile indicated that the most expensive statement in the tagbar is calling ctags.exe. which took 
almost 10 seconds. But it was a total time for running ctags 88 times.

I was not so sure whether one or two calls in 88 times took more than 1 second and the rest of them
were very fast. So, I carefully added some log for timing system('ctags ...') and emitted a log if the duration exceed 1 second.

At last, in my debug log, I finally got the resual: one or two in every 100 system('ctags ..') calls will take 5-6 seconds, which made my gvim seem like freezed.

Very bad experience. Creating new process may delay on windows due to the anti-virus softwares like windows defender which is shipped with windows 10, or it will also caused by scanning some big source file.

Calling system('...') arbitrarily on windows will definitely freeze GVim. Is it possible to introduce background jobs for ctags ? or Can I just turn off tagbar's background refreshing if I haven't open it yet in the current document ?

If so, using tarbar on windows will become much more convenience.

**Comment by skywind3000** [comment] 2018-01-27 14:56
I present my debug log to see how often it happens:

```
[2018-01-27 01:41:58] [vinegar] D:\acm\github\vim\etc\z.sh
[2018-01-27 13:37:58] [vinegar] D:\acm\github\vim\lib\fasd.py
[2018-01-27 17:12:36] [vinegar] d:\acm\github\vim\asc\keymaps.vim
[2018-01-27 17:21:46] takes too long to call ctags: 5.005952s
[2018-01-27 19:27:31] takes too long to call ctags: 6.508376s
[2018-01-27 20:45:25] takes too long to call ctags: 2.094264s
[2018-01-27 21:44:00] [vinegar] D:\acm\github\vim\lib\fasd.py
[2018-01-27 21:48:48] takes too long to call ctags: 6.155538s
[2018-01-27 22:03:37] [vinegar] D:\acm\github\vim\lib\compinit.py
[2018-01-27 22:18:09] [vinegar] D:\acm\github\vim\lib\compinit.py
[2018-01-27 22:21:27] takes too long to call ctags: 6.006248s
[2018-01-27 22:54:03] [vinegar] C:\Users\Linwei\_vimrc
```

**Comment by alerque** [comment] 2020-05-29 20:02
You're right this is an issue, and perhaps the most serious issue making *tagbar* something not everybody wants to leave running. I'm going to close this as a duplicate of a later issue with a more actionable title, but here's to hoping for a fix!

**Closed by alerque** 2020-05-29 20:02 UTC
