### ISSUE TITLE
New tree construction algorithm throws errors on unknown scopes

### ISSUE THREAD

**Issue by IngoHeimbach** [majutsushi/tagbar#397] opened 2017-02-16 08:19 UTC
Hey,
I'm using tagbar together with universal ctags. If any of my C(++) files contain static functions, ctags marks them with *file scope* (`f`) but tagbar doesn't know how to handle that and throws the following errors:
```
Error detected while processing function <SNR>131_AutoUpdate[63]..<SNR>131_ProcessFile[75]..<SNR>131_ParseTagline[106]..<SNR>131_add_tag_recursive[135]..<SNR>131_add_tag_recursive[83]..<SNR>131_create_pseudotag:
E716: Key not present in Dictionary: f
Error detected while processing function <SNR>131_AutoUpdate[63]..<SNR>131_ProcessFile[75]..<SNR>131_ParseTagline[106]..<SNR>131_add_tag_recursive[135]..<SNR>131_add_tag_recursive[83]..<SNR>131_create_pseudotag:
E15: Invalid expression: a:typeinfo.kind2scope[a:parent.fields.kind]
```
If I add `f` as a scope to the tagbar settings for C and C++, tagbar works fine. Is it possible to just ignore unknown scopes?

**Comment by michaelmior** [comment] 2017-02-17 16:21
Seeing this same error with Ruby.

**Comment by datanoise** [comment] 2017-02-17 21:17
same issue here. looks like this change fixes it for me:

```diff
diff --git a/autoload/tagbar.vim b/autoload/tagbar.vim
index 2d54fc3..a7a309e 100644
--- a/autoload/tagbar.vim
+++ b/autoload/tagbar.vim
@@ -2706,7 +2706,11 @@ endfunction
 function! s:create_pseudotag(name, parent, kind, typeinfo, fileinfo) abort
     if !empty(a:parent)
         let curpath = a:parent.fullpath
-        let pscope  = a:typeinfo.kind2scope[a:parent.fields.kind]
+        if has_key(a:typeinfo.kind2scope, a:parent.fields.kind)
+            let pscope  = a:typeinfo.kind2scope[a:parent.fields.kind]
+        else
+            let pscope = ''
+        endif
     else
         let curpath = ''
         let pscope  = ''
```

**Comment by majutsushi** [comment] 2017-02-18 02:49
Odd, I'm not able to reproduce the issue. Does anyone have an example file I could try?
Ignoring the parent scope as in the patch above would work of course, but would also show the tag in the wrong position, so I would like to be able to reproduce this to hopefully find a better solution. Thanks!

**Comment by datanoise** [comment] 2017-02-18 02:51
Try this ruby file: [fileutils.rb](https://github.com/ruby/ruby/blob/trunk/lib/fileutils.rb)

**Comment by majutsushi** [comment] 2017-02-18 03:49
Thanks again for the example. It turns out that at least the Ruby case was the result of two issues: one is that a configuration was missing that functions/methods in Ruby create a class scope in Exuberant Ctags, and another one that the output of Exuberant Ctags in this case is actually incorrect. I've fixed the configuration and also committed a slightly simplified version of the above patch to prevent similar issues from throwing an error in the future.

I'm curious whether the C/C++ error is completely solved now or whether the display will be incorrect due to incorrect configuration. Exuberant Ctags and Universal Ctags keep diverging and so I'm currently working on completely separating the two to make configuration differences easier to deal with in the future.

**Comment by michaelmior** [comment] 2017-02-18 05:02
Thanks! That fixed the problem for me :)

**Comment by IngoHeimbach** [comment] 2017-02-19 11:36
I have tested your patch with a very simple c and cpp file and used both exuberant and universal ctags. Both files contain only one static function:
```c
static void test() {
}
```
In all four cases, the tagbar window showed the following output:
```
functions
  -test()
```
Works perfectly, thanks! :)

**Comment by majutsushi** [comment] 2017-04-07 14:31
Thanks for confirming!

**Closed by majutsushi** 2017-04-07 14:31 UTC
Labels: bug
