### ISSUE TITLE
Issue with universal-ctags installed via snap

### ISSUE THREAD

**Issue by marcusboon** [majutsushi/tagbar#568] opened 2019-12-09 13:38 UTC
### Environment

* Ubuntu 18.04
* ViM:
`VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Jun 06 2019 17:31:41)`
* Universal-ctags:
`Universal Ctags 0.0.0(9fcdb065), Copyright (C) 2015 Universal Ctags Team`
* ViM plugins installed via pathogen:
```
master    => bundle/ctrlp
master    => bundle/delimitmate
master    => bundle/gundo
master    => bundle/mwutils
master    => bundle/nerdtree
master    => bundle/phpcomplete.vim
master    => bundle/supertab
master    => bundle/syntastic
master    => bundle/tagbar
master    => bundle/tagbar-phpctags
master    => bundle/tlib
master    => bundle/vawa
master    => bundle/vdebug
master    => bundle/vim-fugitive
master    => bundle/vim-snipmate
master    => bundle/vim-snippets
```

### Issue

Recently switched from exuberant-ctags (`Version: 1:5.9~svn20110310-11`) to universal-ctags and tagbar stopped working (well it does not spit out any errors in `:messages` but now it just shows `"no tags found`).

Using phpctags and reinstalling the old exuberant-ctags seems to work fine. Also generating tags using the universal-ctags and using them to jump around in vim also seems fine. It's just tagbar that seems to bork with it. Have attached debug logs.
[tagbardebug.zip](https://github.com/majutsushi/tagbar/files/3939908/tagbardebug.zip)

**Comment by alerque** [comment] 2019-12-09 14:51
Is `ctags` in your path? You can try from inside Vim with `:!ctags` just to see if it finds the binary.

You can manually configure a path to your executable too, but if it's in your path it shouldn't be necessary.

**Comment by marcusboon** [comment] 2019-12-09 21:32
Doing `:!ctags` gives me:

```
ctags: No files specified. Try "ctags --help".

shell returned 1

Press ENTER or type command to continue
```

**Comment by alerque** [comment] 2019-12-11 08:12
Looking at the debug log it's pretty clear `ctags` is being found and the version deduced. The issue seems to be it can't read the temporary file used to pass the buffer contents. I'm guessing this has something to do with the way the snap package is installed. It is likely sandboxed in some way that it does not have read access to the host's `/tmp` file system.

This is probably something that needs to be either fixed or configured from the snap package side of things, not this plugin. I'm a little out of my depth because I've never done anything with snaps before. Does anybody here know how to fix this?

**Comment by marcusboon** [comment] 2019-12-14 07:42
For now I’ve built universal-Ctags manually for Ubuntu 18.04 machines and used the apt packages for Ubuntu 19.10 machines. You can close if you’d like.

**Comment by alerque** [comment] 2019-12-14 09:22
I think I'll leave this open for now because it's something others might run into, and we might be able to mitigate it. Perhaps by writing directly to a pipeline instead of a temp file, or by moving the temp file into the PWD instead of using the temp file location (that would be less than ideal for other reasons). Anyway, when somebody comes along that understands the restrictions on snap packages and how to work with them well it would be nice to see this fixed.

**Comment by stevenengler** [comment] 2020-05-29 04:02
I also don't know a good solution to this, but as a workaround it's easy enough to change:

```
diff --git a/autoload/tagbar.vim b/autoload/tagbar.vim
index d210b8c..bbd3d52 100644
--- a/autoload/tagbar.vim
+++ b/autoload/tagbar.vim
@@ -1355,7 +1355,7 @@ function! s:ExecuteCtagsOnFile(fname, realfname, typeinfo) abort
         let ctags_bin = g:tagbar_ctags_bin
     endif

-    let ctags_cmd = s:EscapeCtagsCmd(ctags_bin, ctags_args, a:fname)
+    let ctags_cmd = s:EscapeCtagsCmd(ctags_bin, ctags_args, a:realfname)
     if ctags_cmd ==# ''
         return ''
     endif
```

Note: I don't know how tagbar actually works, so I don't know if this breaks anything. I'm not proposing this as a fix, but it's a workaround for anyone else who runs into this problem.

The problem is that the universal ctags snap cannot read from /tmp (`ctags: Warning: cannot open input file "/tmp/vaLGmG7/2.rs" : No such file or directory`). If universal ctags offered an option to read a file from standard input, that would fix the problem. Otherwise I don't see a good solution. The standard output redirect is not a problem since it happens outside of the snap.

**Comment by alerque** [comment] 2020-05-29 08:48
@stevenengler I'm confused, how does changing the command used to launch ctags as in your diff change it's ability to read from `/tmp`? Or does that fix something else, not that problem?

**Comment by stevenengler** [comment] 2020-05-29 17:10
@alerque There is no way for the snap to read from `/tmp`, so the above change runs ctags on the original file (for example `/home/user/src/myfile.rs`), instead of on tagbar's temporary copy at `/tmp/vaLGmG7/2.rs`. If the original file is stored somewhere in `/tmp`, then this change doesn't help. But if your source files are somewhere else like in `$HOME`, then this will allow you to use tagbar.

**Comment by alerque** [comment] 2020-05-29 17:33
Thanks, I missed that was the *data file* not the file name of ctags!

I just read through the code trying to figure out why tagbar is using temporary copies of the files at all:

https://github.com/majutsushi/tagbar/blob/2a1486447aa62e47faeb98e43fe75c50007870b3/autoload/tagbar.vim#L1185-L1196

I think this makes sense to have *as an option*, but it shouldn't be the only way we function. For me with a giant block of RAM assigned to back `/tmp`, writing the buffer out to it is pretty cheap. At the same time on my laptop where RAM is at a premium but it has a fast SSD I don't bother with that and the extra write operation is actually going to slow the whole thing down.

My first idea is that we should just add an option flag to eschew this cache mechanism. Network file systems are a lot less common than they used to be and I bet for a fair number of people this is actually slowing things down rather than speeding them up.

A second idea is that at least on most platforms we should be able to write the buffer directly to a pipeline into the `ctags` process and save it from any kind of disk IO.

**Comment by alerque** [comment] 2020-05-29 18:06
@stevenengler Can you have a go with the branch I just posted in a PR at #610? You'll need to set this in your init file:

```viml
let g:tagbar_use_cache = 0
```

**Comment by stevenengler** [comment] 2020-05-29 18:39
@alerque Thanks for looking into this so quickly! Yep that works as long as your file is in a directory that the snap is allowed to access (such as most files in your home directory). So while it would be nice if ctags allowed you to pass the file contents using a pipe (then it would work for all files), your change is definitely an improvement compared to existing tagbar.

Also, it seems that tagbar is already designed to catch the error I wrote in my first post: `ctags: Warning: cannot open input file`

https://github.com/majutsushi/tagbar/blob/2a1486447aa62e47faeb98e43fe75c50007870b3/autoload/tagbar.vim#L1363-L1365

But the code catches the phrase `cannot open source file` while universal ctags returns `cannot open input file`. I think this `if` condition should be changed to match both the phrase `source file` and `input file`.

**Comment by alerque** [comment] 2020-05-29 18:57
@stevenengler Done, can you confirm whether that works? We probably need to check all error message parsing to see if we're catching current ones!

**Comment by stevenengler** [comment] 2020-05-29 19:03
@alerque Yep that works great! Now if I re-enable the cache and call `:messages`, I get the `Tagbar: Could not execute ctags [...]` debug messages, which should hopefully help anyone in the future if they run into this problem. Before, there were no messages or warnings, tagbar just didn't show any tags.

**Closed** 2020-05-29 19:42 UTC
Labels: ctags
