### ISSUE TITLE
neovim got segmentation fault

### ISSUE THREAD

**Issue by lasypig** [majutsushi/tagbar#386] opened 2016-12-21 03:54 UTC
What I opened is a C file. I modify it and save(:w), I got the following Error message:
```
Error detected while processing function <SNR>89_AutoUpdate[52]..<SNR>89_ProcessFile[26]..295:                                                                                                         
line   28:                                                                                                                                                                                             
E716: Key not present in Dictionary: kinds                                                                                                                                                             
Press ENTER or type command to continue                                                                                                                                                                
Error detected while processing function <SNR>89_AutoUpdate[52]..<SNR>89_ProcessFile[26]..295:                                                                                                         
line   28:                                                                                                                                                                                             
E15: Invalid expression: a:typeinfo.kinds                                                                                                                                                              
Press ENTER or type command to continueSegmentation fault
```

My neovim version is:
```
NVIM 0.2.0-dev
Build type: RelWithDebInfo
Compilation: /usr/bin/i686-linux-gnu-gcc -g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -DDISABLE_LOG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector --param ssp-buffer-size=4 -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -D_GNU_SOURCE -I/build/neovim-AXdBgb/neovim-0.1.5ubuntu1+git201612182239+2975+22~ubuntu14.04.1/build/config -I/build/neovim-AXdBgb/neovim-0.1.5ubuntu1+git201612182239+2975+22~ubuntu14.04.1/src -I/build/neovim-AXdBgb/neovim-0.1.5ubuntu1+git201612182239+2975+22~ubuntu14.04.1/.deps/usr/include -I/build/neovim-AXdBgb/neovim-0.1.5ubuntu1+git201612182239+2975+22~ubuntu14.04.1/.deps/usr/include -I/build/neovim-AXdBgb/neovim-0.1.5ubuntu1+git201612182239+2975+22~ubuntu14.04.1/.deps/usr/include -I/build/neovim-AXdBgb/neovim-0.1.5ubuntu1+git201612182239+2975+22~ubuntu14.04.1/.deps/usr/include -I/build/neovim-AXdBgb/neovim-0.1.5ubuntu1+git201612182239+2975+22~ubuntu14.04.1/.deps/usr/include -I/build/neovim-AXdBgb/neovim-0.1.5ubuntu1+git201612182239+2975+22~ubuntu14.04.1/.deps/usr/include -I/usr/include -I/build/neovim-AXdBgb/neovim-0.1.5ubuntu1+git201612182239+2975+22~ubuntu14.04.1/build/src/nvim/auto -I/build/neovim-AXdBgb/neovim-0.1.5ubuntu1+git201612182239+2975+22~ubuntu14.04.1/build/include
Compiled by root@lcy01-36

Optional features included (+) or not (-): +acl   +iconv    +jemalloc +tui      
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"
```

**Comment by gyermolenko** [comment] 2016-12-21 11:41
I have similar issue: I open `.py` file in neovim and get this segfault. 
I couldn't reproduce it in vim, BUT in neovim reproduction of issue is not like 1-2-3 step to repeat.

**Comment by mhinz** [comment] 2016-12-22 13:13
Do you have any tagbar options set?

I can't reproduce it (`:w` in a C file) using the master of Neovim and tagbar.

**Comment by morbit85** [comment] 2016-12-23 00:53
I have same issue on js file. Reproduce: 

1. `:w`
2. wait 10 seconds
3. `<Esc>`

`call s:debug('DBG vars: ' . string(typeinfo) . " " . a:ftype . " ". a:fname)` in line 2153 gives 
`1970-01-01 07:15:14.851794: DBG0 vars: {} javascript /mnt/nix_hdd/src/nodejs-agent/lib/controller.js`
After that `s:FileInfo.New()` in line 2170 gives error

**Comment by mhinz** [comment] 2016-12-23 02:06
@morbit85 And just to be sure.. it works with Vim?

Looking through the code, `typeinfo` should only be empty if `s:InitTypes()` wasn't run yet.

**Comment by majutsushi** [comment] 2016-12-23 07:07
There seem to be two different issues here. If Neovim segfaults then that is a bug in Neovim, not in Tagbar.

As for why the `typeinfo` doesn't seem to be set I would need some more information. What kind of program do you use to generate javascript tags? One of the javascript-specific ones? Universal Ctags? Exuberant Ctags? Also, what's your Tagbar configuration? Do you have any autocommands related to Tagbar? It would be helpful if you could generate a logfile as described in `:h tagbar-issues`.

**Comment by lasypig** [comment] 2016-12-23 07:43
@majutsushi I do as `:h tagbar-issues` 
  1. Open nvim without loading any files at dir `/home/wangxb/work/core`.
  2. Run `:TagbarDebug`.
  3. Open file `:e modules/soe/SOEproducerCVA.c`.
  4. Open Tagbar.
  5. Error apears sevral times and got segment fault.

Here is `tagbardebug.log`:
```
1970-01-01 14:19:50.615947: goto_win(): wincmd p, 1
1970-01-01 14:19:51.842198: AutoUpdate called [/home/wangxb/work/core/modules/soe/SOEproducerCVA.c]
1970-01-01 14:19:51.842289: Vim filetype: 'c', sanitized filetype: 'c'
1970-01-01 14:19:51.842328: Checking if file is valid [/home/wangxb/work/core/modules/soe/SOEproducerCVA.c]
1970-01-01 14:19:51.842447: File data seems up to date [/home/wangxb/work/core/modules/soe/SOEproducerCVA.c]
1970-01-01 14:19:51.842554: Setting current file [/home/wangxb/work/core/modules/soe/SOEproducerCVA.c]
1970-01-01 14:19:51.842701: goto_win(): wincmd p, 1
1970-01-01 14:19:51.842769: goto_win(): 3wincmd w, 1
1970-01-01 14:19:51.843956: goto_win(): 2wincmd w, 1
1970-01-01 14:19:52.340128: goto_win(): 3wincmd w, 1
1970-01-01 14:19:52.340308: goto_win(): 2wincmd w, 1
1970-01-01 14:19:52.341826: goto_win(): 3wincmd w, 1
1970-01-01 14:19:52.341999: goto_win(): 2wincmd w, 1
1970-01-01 14:20:03.362690: goto_win(): 3wincmd w, 1
1970-01-01 14:20:03.362934: goto_win(): 2wincmd w, 1
1970-01-01 14:20:11.275445: goto_win(): 3wincmd w, 1
1970-01-01 14:20:11.275690: goto_win(): 2wincmd w, 1
1970-01-01 14:20:11.324099: goto_win(): 3wincmd w, 1
1970-01-01 14:20:11.325264: goto_win(): 2wincmd w, 1
1970-01-01 14:20:20.596199: goto_win(): 3wincmd w, 1
1970-01-01 14:20:20.596436: goto_win(): 2wincmd w, 1
1970-01-01 14:20:20.699140: goto_win(): 3wincmd w, 1
1970-01-01 14:20:20.700582: goto_win(): 2wincmd w, 1
1970-01-01 14:20:31.884219: goto_win(): 3wincmd w, 1
1970-01-01 14:20:31.884451: goto_win(): 2wincmd w, 1
1970-01-01 14:20:31.986321: goto_win(): 3wincmd w, 1
1970-01-01 14:20:31.987474: goto_win(): 2wincmd w, 1
1970-01-01 14:20:46.682537: goto_win(): 3wincmd w, 1
1970-01-01 14:20:46.682717: goto_win(): 2wincmd w, 1
1970-01-01 14:20:55.495353: AutoUpdate called [/home/wangxb/work/core/SOEproducerCVA.c]
1970-01-01 14:20:55.495589: Vim filetype: '', sanitized filetype: ''
1970-01-01 14:20:55.495654: Checking if file is valid [/home/wangxb/work/core/SOEproducerCVA.c]
1970-01-01 14:20:55.495710: Empty filename or type
1970-01-01 14:20:55.495759: Not a valid file, stopping processing
1970-01-01 14:21:21.942930: goto_win(): 3wincmd w, 1
1970-01-01 14:21:21.953466: goto_win(): 2wincmd w, 1
1970-01-01 14:21:21.954084: goto_win(): 3wincmd w, 1
1970-01-01 14:21:21.954330: goto_win(): 2wincmd w, 1
1970-01-01 14:21:22.057143: goto_win(): 3wincmd w, 1
1970-01-01 14:21:22.058351: goto_win(): 2wincmd w, 1
1970-01-01 14:22:01.864910: goto_win(): 3wincmd w, 1
1970-01-01 14:22:01.865174: goto_win(): 2wincmd w, 1
1970-01-01 14:22:01.966957: goto_win(): 3wincmd w, 1
1970-01-01 14:22:01.968123: goto_win(): 2wincmd w, 1
```

**Comment by morbit85** [comment] 2016-12-23 21:47
I use Exuberant Ctags, `typeinfo` is not empty on previous call of `s:ProcessFile()`. 
```
Error detected while processing function <SNR>85_AutoUpdate[52]..<SNR>85_ProcessFile[26]..60:                                 
line   28:                                                                                                                    
E716: Key not present in Dictionary: kinds                                                                                    
Press ENTER or type command to continue                                                                                       
Error detected while processing function <SNR>85_AutoUpdate[52]..<SNR>85_ProcessFile[26]..60:                                 
line   28:                                                                                                                    
E15: Invalid expression: a:typeinfo.kinds
SegmentationFault
```
log:
```
1970-01-01 15:14:46.973803: AutoUpdate called [/mnt/nix_hdd/src/nodejs-agent/]
1970-01-01 15:14:46.973983: Vim filetype: '', sanitized filetype: ''
1970-01-01 15:14:46.974040: Checking if file is valid [/mnt/nix_hdd/src/nodejs-agent/]
1970-01-01 15:14:46.974089: Empty filename or type
1970-01-01 15:14:46.974134: Not a valid file, stopping processing
                                1970-01-01 15:14:50.473976: AutoUpdate called [/mnt/nix_hdd/src/nodejs-agent/lib/controller.js]
1970-01-01 15:14:50.480816: Vim filetype: 'javascript', sanitized filetype: 'javascript'
1970-01-01 15:14:50.480899: Checking if file is valid [/mnt/nix_hdd/src/nodejs-agent/lib/controller.js]
1970-01-01 15:14:50.481071: New file, processing [/mnt/nix_hdd/src/nodejs-agent/lib/controller.js]
1970-01-01 15:14:50.481123: ProcessFile called [/mnt/nix_hdd/src/nodejs-agent/lib/controller.js]
1970-01-01 15:14:50.481173: Checking if file is valid [/mnt/nix_hdd/src/nodejs-agent/lib/controller.js]
1970-01-01 15:14:50.481470: typeinfo for file to process: {'ctagstype': 'javascript', 'ftype': 'javascript', 'kinddict': {'p': 2, 'c': 1, 'f': 4, 'v': 0, 'm': 3}, 'sro': '.', 'getKind': function('58'), 'createKinddict': function('59'), 'kind2scope': {'p': 'property', 'c': 'class', 'f': 'function', 'm': 'method'}, 'scope2kind': {'function': 'f', 'class': 'c'}, 'New': function('57'), 'kinds': [{'short': 'v', 'long': 'global variables', 'fold': 0, 'stl': 0}, {'short': 'c', 'long': 'classes', 'fold': 0, 'stl': 1}, {'short': 'p', 'long': 'properties', 'fold': 0, 'stl': 0}, {'short': 'm', 'long': 'methods', 'fold': 0, 'stl': 1}, {'short': 'f', 'long': 'functions', 'fold': 0, 'stl': 1}]}
1970-01-01 15:14:50.482244: ExecuteCtagsOnFile called [/tmp/nvimQz3y7y/3.js]
1970-01-01 15:14:50.482384: EscapeCtagsCmd called
1970-01-01 15:14:50.482427: ctags_bin: ctags-exuberant
1970-01-01 15:14:50.482479: ctags_args (is a list): ['-f', '-', '--format=2', '--excmd=pattern', '--fields=nksSaf', '--extra=', '--file-scope=yes', '--sort=no', '--append=no', '--language-force=javascript', '--javascript-kinds=vcpmf']
1970-01-01 15:14:50.482669: Escaped ctags command: 'ctags-exuberant' '-f' '-' '--format=2' '--excmd=pattern' '--fields=nksSaf' '--extra=' '--file-scope=yes' '--sort=no' '--append=no' '--language-force=javascript' '--javascript-kinds=vcpmf' '/tmp/nvimQz3y7y/3.js'
1970-01-01 15:14:50.482744: Executing ctags command: 'ctags-exuberant' '-f' '-' '--format=2' '--excmd=pattern' '--fields=nksSaf' '--extra=' '--file-scope=yes' '--sort=no' '--append=no' '--language-force=javascript' '--javascript-kinds=vcpmf' '/tmp/nvimQz3y7y/3.js'
1970-01-01 15:14:50.486423: "lib/controller.js" 771L, 24954C
1970-01-01 15:14:50.486501: Exit code: 0
1970-01-01 15:14:50.506772: Ctags executed successfully
1970-01-01 15:14:50.506923: Filetype tag kinds: ['p', 'c', 'f', 'v', 'm']
1970-01-01 15:14:50.506974: Parsing ctags output
1970-01-01 15:14:50.514601: Processing scoped tags
1970-01-01 15:14:50.521789: Number of top-level tags: 7
1970-01-01 15:14:50.521880: Processing kind: v, number of tags: 0
1970-01-01 15:14:50.521945: Processing kind: c, number of tags: 0
1970-01-01 15:14:50.521997: Processing kind: p, number of tags: 0
1970-01-01 15:14:50.522047: Processing kind: m, number of tags: 0
1970-01-01 15:14:50.522095: Processing kind: f, number of tags: 0
1970-01-01 15:14:50.524420: Setting current file [/mnt/nix_hdd/src/nodejs-agent/lib/controller.js]
1970-01-01 15:14:50.524685: AutoUpdate finished successfully
1970-01-01 15:14:50.556179: AutoUpdate called [/mnt/nix_hdd/src/nodejs-agent/lib/controller.js]
1970-01-01 15:14:50.556354: Vim filetype: 'javascript', sanitized filetype: 'javascript'
1970-01-01 15:14:50.556440: Checking if file is valid [/mnt/nix_hdd/src/nodejs-agent/lib/controller.js]
1970-01-01 15:14:50.556622: File data seems up to date [/mnt/nix_hdd/src/nodejs-agent/lib/controller.js]
1970-01-01 15:14:50.556758: Setting current file [/mnt/nix_hdd/src/nodejs-agent/lib/controller.js]
1970-01-01 15:14:50.557005: AutoUpdate finished successfully
1970-01-01 15:14:50.581352: AutoUpdate called [/mnt/nix_hdd/src/nodejs-agent/lib/controller.js]
1970-01-01 15:14:50.581492: Vim filetype: 'javascript', sanitized filetype: 'javascript'
1970-01-01 15:14:50.581570: Checking if file is valid [/mnt/nix_hdd/src/nodejs-agent/lib/controller.js]
1970-01-01 15:14:50.581749: File data seems up to date [/mnt/nix_hdd/src/nodejs-agent/lib/controller.js]
1970-01-01 15:14:50.581903: Setting current file [/mnt/nix_hdd/src/nodejs-agent/lib/controller.js]
1970-01-01 15:14:50.582144: AutoUpdate finished successfully
1970-01-01 15:14:52.601284: AutoUpdate called [/mnt/nix_hdd/src/nodejs-agent/lib/controller.js]
1970-01-01 15:14:52.601682: Vim filetype: 'javascript', sanitized filetype: 'javascript'
1970-01-01 15:14:52.601869: Checking if file is valid [/mnt/nix_hdd/src/nodejs-agent/lib/controller.js]
1970-01-01 15:14:52.602466: File data seems up to date [/mnt/nix_hdd/src/nodejs-agent/lib/controller.js]
1970-01-01 15:14:52.602948: Setting current file [/mnt/nix_hdd/src/nodejs-agent/lib/controller.js]
1970-01-01 15:14:52.603736: AutoUpdate finished successfully
                                        1970-01-01 15:14:53.800246: AutoUpdate called [/mnt/nix_hdd/src/nodejs-agent/lib/controller.js]
1970-01-01 15:14:53.800374: Vim filetype: 'javascript', sanitized filetype: 'javascript'
1970-01-01 15:14:53.800673: Checking if file is valid [/mnt/nix_hdd/src/nodejs-agent/lib/controller.js]
1970-01-01 15:14:53.800865: File data outdated, updating [/mnt/nix_hdd/src/nodejs-agent/lib/controller.js]
1970-01-01 15:14:53.800918: ProcessFile called [/mnt/nix_hdd/src/nodejs-agent/lib/controller.js]
1970-01-01 15:14:53.800965: Checking if file is valid [/mnt/nix_hdd/src/nodejs-agent/lib/controller.js]
1970-01-01 15:14:53.801230: typeinfo for file to process: {'ctagstype': 'javascript', 'ftype': 'javascript', 'kinddict': {'p': 2, 'c': 1, 'f': 4, 'v': 0, 'm': 3}, 'sro': '.', 'getKind': function('58'), 'createKinddict': function('59'), 'kind2scope': {'p': 'property', 'c': 'class', 'f': 'function', 'm': 'method'}, 'scope2kind': {'function': 'f', 'class': 'c'}, 'New': function('57'), 'kinds': [{'short': 'v', 'long': 'global variables', 'fold': 0, 'stl': 0}, {'short': 'c', 'long': 'classes', 'fold': 0, 'stl': 1}, {'short': 'p', 'long': 'properties', 'fold': 0, 'stl': 0}, {'short': 'm', 'long': 'methods', 'fold': 0, 'stl': 1}, {'short': 'f', 'long': 'functions', 'fold': 0, 'stl': 1}]}
1970-01-01 15:14:53.801992: ExecuteCtagsOnFile called [/tmp/nvimQz3y7y/8.js]
1970-01-01 15:14:53.802127: EscapeCtagsCmd called
1970-01-01 15:14:53.802169: ctags_bin: ctags-exuberant
1970-01-01 15:14:53.802219: ctags_args (is a list): ['-f', '-', '--format=2', '--excmd=pattern', '--fields=nksSaf', '--extra=', '--file-scope=yes', '--sort=no', '--append=no', '--language-force=javascript', '--javascript-kinds=vcpmf']
1970-01-01 15:14:53.802413: Escaped ctags command: 'ctags-exuberant' '-f' '-' '--format=2' '--excmd=pattern' '--fields=nksSaf' '--extra=' '--file-scope=yes' '--sort=no' '--append=no' '--language-force=javascript' '--javascript-kinds=vcpmf' '/tmp/nvimQz3y7y/8.js'
1970-01-01 15:14:53.802488: Executing ctags command: 'ctags-exuberant' '-f' '-' '--format=2' '--excmd=pattern' '--fields=nksSaf' '--extra=' '--file-scope=yes' '--sort=no' '--append=no' '--language-force=javascript' '--javascript-kinds=vcpmf' '/tmp/nvimQz3y7y/8.js'
1970-01-01 15:14:53.806001: No matching autocommands
1970-01-01 15:14:53.806080: Exit code: 0
1970-01-01 15:14:53.822877: Ctags executed successfully
1970-01-01 15:14:53.823003: Filetype tag kinds: ['p', 'c', 'f', 'v', 'm']
1970-01-01 15:14:53.823050: Parsing ctags output
1970-01-01 15:14:53.830888: Processing scoped tags
1970-01-01 15:14:53.838181: Number of top-level tags: 7
1970-01-01 15:14:53.838254: Processing kind: v, number of tags: 0
1970-01-01 15:14:53.838308: Processing kind: c, number of tags: 0
1970-01-01 15:14:53.838359: Processing kind: p, number of tags: 0
1970-01-01 15:14:53.838408: Processing kind: m, number of tags: 0
1970-01-01 15:14:53.838455: Processing kind: f, number of tags: 0
1970-01-01 15:14:53.840563: Setting current file [/mnt/nix_hdd/src/nodejs-agent/lib/controller.js]
1970-01-01 15:14:53.840799: AutoUpdate finished successfully
1970-01-01 15:14:56.364396: AutoUpdate called [/mnt/nix_hdd/src/nodejs-agent/lib/controller.js]
1970-01-01 15:14:56.364529: Vim filetype: 'javascript', sanitized filetype: 'javascript'
1970-01-01 15:14:56.364586: Checking if file is valid [/mnt/nix_hdd/src/nodejs-agent/lib/controller.js]
1970-01-01 15:14:56.364767: File data seems up to date [/mnt/nix_hdd/src/nodejs-agent/lib/controller.js]
1970-01-01 15:14:56.364911: Setting current file [/mnt/nix_hdd/src/nodejs-agent/lib/controller.js]
1970-01-01 15:14:56.365147: AutoUpdate finished successfully
1970-01-01 15:15:10.203695: AutoUpdate called [/mnt/nix_hdd/src/nodejs-agent/lib/controller.js]
1970-01-01 15:15:10.203921: Vim filetype: 'javascript', sanitized filetype: 'javascript'
1970-01-01 15:15:10.204044: Checking if file is valid [/mnt/nix_hdd/src/nodejs-agent/lib/controller.js]
1970-01-01 15:15:10.204215: File data outdated, updating [/mnt/nix_hdd/src/nodejs-agent/lib/controller.js]
1970-01-01 15:15:10.204272: ProcessFile called [/mnt/nix_hdd/src/nodejs-agent/lib/controller.js]
1970-01-01 15:15:10.204327: Checking if file is valid [/mnt/nix_hdd/src/nodejs-agent/lib/controller.js]
```

**Comment by morbit85** [comment] 2016-12-23 22:16
Stacktrace is at neovim/neovim#5817

**Comment by majutsushi** [comment] 2016-12-24 03:51
Hmm, if the typeinfo is available at some point and then suddenly vanishes then this sounds like a bug in Neovim as well, because there is no code in Tagbar that removes initialized types. Reading the comments in that bug report seems to confirm that this is a possibility. So I think it would be useful to wait for the Neovim bug to be fixed before investigating this further.

**Comment by languitar** [comment] 2017-01-05 12:54
I am still getting these issues with a neovim version from today

**Comment by erahhal** [comment] 2017-01-13 20:29
I am still seeing an issue as well.

**Comment by justinmk** [comment] 2017-02-11 06:23
Should be fixed on [neovim master](https://github.com/neovim/neovim/commit/14fc4825f392bca33b2873c317d24663883b681d).

**Comment by majutsushi** [comment] 2017-02-13 03:04
Thanks, I'm going to close this then.

**Closed by majutsushi** 2017-02-13 03:04 UTC
Labels: neovim-bug
