### ISSUE TITLE
Ctags not recognized

### ISSUE THREAD

**Issue by floGik** [majutsushi/tagbar#366] opened 2016-11-23 11:57 UTC
I have the weirdest error...
```
Tagbar: Ctags doesn't seem to be Exuberant Ctags!
BSD ctags will NOT WORK. Please download Exuberant Ctags from ctags.sourceforge.net and install it in a directory in your $PATH or set g:tagbar_ctags_bin.                              
Executed command: "'/usr/local/bin/ctags' --version"
Command output:
Exuberant Ctags 5.8, Copyright (C) 1996-2009 Darren Hiebert
  Compiled: Jan 24 2016, 04:13:50
  Addresses: <dhiebert@users.sourceforge.net>, http://ctags.sourceforge.net
  Optional compiled features: +wildcards, +regex
Exit code: -1
```
It doesn't seem to be Exuberant Ctags but the output clearly shows that it is... also the latest version no less.

I'm on vim8.0 on void linux. Any idea why this happens?

**Comment by majutsushi** [comment] 2016-11-25 04:43
This is a duplicate of #352. Short version: It's a bug in Vim that's fixed in version 8.0.71.

**Closed by majutsushi** 2016-11-25 04:43 UTC
