### ISSUE TITLE
Is there a way to disable tagbar except for showing the current function name in vim-airline?

### ISSUE THREAD

**Issue by himat** [majutsushi/tagbar#626] opened 2020-06-28 16:48 UTC
Tagbar is noticeably slow to start up for me when I first open any file with vim.
So I want to disable it by default.

The only functionality I want from tagbar is to see the current function name in my airline status bar.
Is it possible to disable tagbar from starting on file opening, and only have it work to show the current function in airline?

Otherwise, do you know of a different vim plugin that can show the function name in airline?

**Comment by alerque** [comment] 2020-06-28 18:09
As written this request is kind of contradictory: we can't supply the info for airline if we haven't launched and generated tags. I think what you really want is #477 or #532 which should deal with the performance issue a bit. Also note that once tag files are generated for a project it should be a little lighter weight on the second launch.

I'm closing this as I believe it's a duplicate of the background launch / async run options already tracked in other issues.

**Closed by alerque** 2020-06-28 18:09 UTC
